vhdlpp/parse.y
vhdlpp/scope.cc
vhdlpp/scope.h

Fix for https://sourceforge.net/p/iverilog/bugs/942/

bugfix #942: VHDL function bodies in arch declaration not supported

---

vhdlpp/parse_misc.cc
vhdlpp/vtype.cc

Resolved #110

---

vhdlpp/architec_emit.cc
vhdlpp/debug.cc
vhdlpp/expression.cc
vhdlpp/expression.h
vhdlpp/expression_debug.cc
vhdlpp/expression_elaborate.cc
vhdlpp/expression_emit.cc
vhdlpp/expression_evaluate.cc
vhdlpp/expression_stream.cc
vhdlpp/library.cc
vhdlpp/parse.y
vhdlpp/parse_misc.cc
vhdlpp/std_funcs.cc
vhdlpp/std_funcs.h
vhdlpp/subprogram.cc
vhdlpp/subprogram.h
vhdlpp/vtype.h
vhdlpp/vtype_emit.cc
vhdlpp/vtype_match.cc

- unary sign operator
- stricter type matching (as it should be in VHDL)
- fixed resize()
- minor bug fixes & refactoring
Updated test suite: https://github.com/orsonmmz/ivtest/tree/resize_fix_test

vhdlpp update

---

PFunction.cc
elab_expr.cc
elab_lval.cc
elab_sig.cc
elaborate.cc
parse.y
pform_pclass.cc
pform_types.h

Fix some weak syntax/symantic checking related to constructors calling the super constructor. Also, handle a compiler error when constructors are otherwise empty.

Fixes for issues #387 and #390

---

.github/test.sh
.github/workflows/test.yml

Some rework of the CI workflow, related to #399, #400, #402 and work towards #398.

ci: add 'test.sh'

---

driver-vpi/Makefile.in

driver-vpi: add DESTDIR to iverilog-vpi install path

---

elab_expr.cc
vpi/v2009_string.c

This implements:
string.atoi
string.atoreal
string.atohex
Fixes #414

Implement the string.atoi method

---

.github/workflows/test.yml

It seems to fail during compilation at the moment,

Add MacOS to CI/GHA

---

net_design.cc

Elaborate parameter types in the scope of the paramter.

---

parse.y

This is the v11 port of PR #457 .

output ports of type real are variables, not wires.

---

parse.y

Task and function item rules are identical. Consolidate them into a single
set of rules to remove some duplicated code.

Consolidate task and function item parser rules

---

tgt-blif/blif.cc

There is now an implicit $unit package that needs to be ignored by
the blif target. Take this opportunity to make the root module checking
for the blif target a bit more robust.

Better handling of root selection for BLIF target.

---

elaborate.cc
ivtest/ivltests/sv_string6.v
ivtest/regress-sv.list
vpi/v2009_string.c

This PR adds support for the <string>.Xtoa() methods. It works by generating the appropriate system task calls to do the work.
Also add a regression test to validate the operation.
The resolves #541 .

String itoa etc

---

Documentation/targets/index.rst
Documentation/targets/pcb.rst
Documentation/targets/verilog95.rst
Documentation/targets/vhdl.rst
Documentation/usage/command_files.rst
Documentation/usage/index.rst
Documentation/usage/installation.rst
Documentation/usage/ivl_target.rst
Documentation/usage/simulation.rst
Documentation/usage/vpi.rst

This finishes up most of the User Guide from the Wiki. Some bits
from the wiki are just too aweful, or obsolete, so are left out.

Documentation: Transferring more content from the wiki

---

.github/workflows/test.yml
Documentation/developer/getting_started.rst
Documentation/developer/index.rst
Documentation/usage/index.rst
Documentation/usage/reporting_issues.rst

This starts the documentation for new contributers. This includes how to contribute pull requests using github, and how to submit issues.

Document getting started as a developer

---

vvp/vthread.cc

Both the `%concati/vec4` and `%pushi/vec4` instructions need to construct a
vector from the immediate value encoded in the instruction. Currently both
these instructions have a custom implementation for that.
Remove the custom implementations from those functions and use the
`get_immediate_rval()` helper function. This removes a bit of duplicated
code.

vvp: `%{concati,pushi}/vec4` use `get_immediate_rval()` helper

---

Documentation/usage/index.rst
Documentation/usage/vvp_debug.rst
Documentation/usage/vvp_flags.rst

Vvp has an interactive debug mode that few seem to be aware of. Document that mode.

vvp: Document the vvp interactive debug mode

---

Documentation/developer/version_stamps.rst

This is another bit that needs to be accounted for when changing versions.

ivtest: Document the ivest/regress-vNN.list file.

---

Documentation/developer/regression_tests.rst
Documentation/usage/vvp_flags.rst
ivtest/gold/dumpfile-vvp-stdout.gold
ivtest/ivltests/dumpfile.v
ivtest/regress-vvp.list
ivtest/run_ivl.py
ivtest/vvp_reg.py
ivtest/vvp_tests/dumpfile.json
vpi/sys_fst.c
vpi/sys_lxt.c
vpi/sys_lxt2.c
vpi/sys_priv.c
vpi/sys_priv.h
vpi/sys_table.c
vpi/sys_vcd.c
vpi/vcd_priv.c
vpi/vcd_priv.h

The -dumpfile=<path> vvp extended argument sets the default nanme to use for the various dumpers. If this flag is not given, the default is "dump". The $dumpfile system task overrides the default or this command line flag.
This commit also factors out all the dumpfile selection code for the various dumper implementations.
This fixes Issue#202

Add support for a command line dumpfile option

---

config.guess
config.sub

See https://github.com/steveicarus/iverilog/issues/903.

Update config.guess and config.sub to add support for riscv64 platform

---

README.md

The README is long and could a bit more user friendly.

README file enhancements

---

elab_expr.cc
eval_tree.cc
ivtest/ivltests/struct_enum_partsel.v
ivtest/ivltests/struct_field_left_right.v
ivtest/regress-vvp.list
ivtest/vvp_tests/struct_enum_partsel.json
ivtest/vvp_tests/struct_field_left_right.json

See referenced issues for the problems this PR addresses

Couple of fixes for struct supports

---

Documentation/developer/getting_started.rst
Documentation/developer/version_stamps.rst

Saw some typos in the developer docs, hope this helps.

typo fixes

---

ivtest/regress-vvp.list

Another small typo in another test suite list

Typo in `regress-vvp.list`
