t-dll-api.cc
t-dll.cc
vpi/sys_scanf.c

This pull request removes two unused static functions and adds the definition of _DEFAULT_SOURCE.
Tested with gcc 5.1 in fedora 22.

Fix 3 compiler warnings

---

vhdlpp/parse_misc.cc
vhdlpp/vtype.cc

To be able to compile the newest sources with gcc on my Debian/Linux testing machine, I had to modify two files.
Otherwise I get the errors:
error: ‘ExpRange::range_dir_t’ is not a class or namespace
The other solution could be to compile with "-std=c++0x" option, which should add scoped enums.
I have not tested it though.

Changes necessary to compile with gcc on Debian/Linux testing

---

aclocal.m4

Hi,
I have detected that "___strtod" is not defined in x86_64-w64-mingw32, as it is in i686-w64-mingw32. Instead, it is defined "__strtod" (with 2 " _ " instead of 3). Therefore, the build fails.
*x86_64-w64-mingw32*
> $ x86_64-w64-mingw32-nm /usr/x86_64-w64-mingw32/lib/libmingwex.a | grep -e "___strtod"
> $ x86_64-w64-mingw32-nm /usr/x86_64-w64-mingw32/lib/libmingwex.a | grep -e "__strtod"
0000000000000500 T __strtodg
0000000000000000 T __strtod
U __strtodg
U __strtodg
U __strtodg
U __strtod
*i686-w64-mingw32*
> $ i686-w64-mingw32-nm /usr/i686-w64-mingw32/lib/libmingwex.a | grep -e "___strtod"
000004f0 T ___strtodg
00000000 T ___strtod
U ___strtodg
U ___strtodg
U ___strtodg
U ___strtod
This commits fixes the issue.

Fix x86_64-w64-mingw32 build: undefined ___strtod

---

PGate.h
elab_scope.cc
parse.y
pform.cc
pform.h
pform_dump.cc

(* my_fancy_attribute *)
foobar1 foobar (clk(clk), rst(rst) ...);
- Modifies PGModule to hold the attribute map (can be verified with pform_dump)
- pform_make_modgate(s) bind the attributes from the parser to the above map
- The attributes from PGModule are inserted into the NetScope of that module
PGModule::elaborate_scope_mod_instances_
- Currently these attributes automatically make it into netlist
- These attributes are accessible via ivl_scope_attr_cnt and ivl_scope_attr_val
from ivl_target.h

Add support to handle attributes at module instantiation sites.

---

compiler.h
driver/main.c
elaborate.cc
main.cc

This commit adds an option (-i) to ignore errors about missing modules.
Ignoring missing modules is really useful for using iverilog as linter in text editors (like Atom or Sublime Text), where you usually only want to check single files without caring about modules on other files.

Added an option for ignoring errors about missing modules

---

driver/main.c

Return and print an error if iverilog is unable to open dependencies
file. User can pass e.g path to existing directory in '-M' option,
which makes fopen to return NULL followed by crash in fclose.

Return if unable to open dependencies file

---

driver/iverilog.man.in
driver/main.c
ivlpp/globals.h
ivlpp/lexor.lex
ivlpp/main.c

Verilog spec has a very nasty system of macros jumping from
file to file, resulting in a global macro scope. We abosolutely
MUST track macro redefinitions and warn user about them.
Signed-off-by: Andrew Andrianov <andrew@ncrmnt.org>

ivlpp: Warn about macro redefinition

---

tgt-vvp/vvp_scope.c
vvp/parse.y

This PR attempts to fix #179 
There are two parts. The first commit simply fixes tgt-vvp so it includes a semicolon after all .port_info statements. This fix is inherently backwards compatible, as current versions of vvp accept the extra semicolon without issue (they think it's an empty statement).
The second commit fixes the parser to be more strict and syntax error when the semicolon is missing. Because this would cause backwards compatibility issues (any vvp files generated on 11.0 dev before this commit is merged will be missing the semicolons), I've delayed the activation of this new stricter rule until 12.0
As vvp refuses to read files from older major versions, by the time work starts on 12.0, vvp will only be expected to parse vvp files generated with the correct semicolon syntax. …

vvp grammar: .port_info statements should require/generate semicolons.

---

README.txt

Added command to run 'autoconf.sh', generating the 'configure' file.

Added missing compilation instruction on README

---

vvp/main.cc
vvp/vpi_modules.cc
vvp/vpi_priv.h
vvp/vvp.man.in

This patch does three main things. First, it reverses the order in which the internal path list is checked so that paths specified with -M are checked first and the default paths are checked last.  Second, it enforces the path count limit to prevent crashes.  Third, it implements the environment variable IVERILOG_VPI_MODULE_PATH to specify a colon-separated list of directories in which to look for VPI modules.

VPI search path updates

---

parse.y

This PR adds support for the Verilog parser so it can accept attribute specifications on module instance port connections and on function calls. Solves issue https://github.com/steveicarus/iverilog/issues/248

Support for attributes on port connections and function calls

---

parse.y
parse_misc.cc
parse_misc.h
pform.cc

While trying to simulate a larger ASIC design (together with some technology libraries), I came across two major annoyances:
- The technology files redefine primitives with the same content in multiple places, and can not easily be altered
- The technology files make heavy use of timing checks, many of them using the unsupported ifnone+edge-sensitive path construct.
In the end I got my simulations working and maybe the changes I needed to do to iverilog can be acceptable for mainline. As altering the vendor libraries is not really an option for me and these two things seem to be commonly used, maybe it can increase adoption of iverilog for such uses.
As it was at times hard for me to figure out, which messages from iverilog are errors and which are warnings, I also tried improving the …

Degrade primitive redefinition and ifnone with edge-sensitive-path to warnings

---

driver/cflexor.lex

cfparse.h defines the YYLTYPE struct in case it has not been defined, and
also declares an extern YYLTYPE cflloc which is used in cflexor.
As cfparse_misc.h defines an extended YYLTYPE, the cflloc instance in
cfparse.c has this extended type, i.e. there is a type mismatch.
Changing the include order in cflexor causes both cflexor.c and
cfparse.c to use the definition from cfparse_misc.h.
This has been uncovered by GCC when using LTO:
```
gcc -flto=8 main.o substit.o cflexor.o cfparse.o -o iverilog 
cfparse.h:105:16: warning: type of 'cflloc' does not match original declaration [-Wlto-type-mismatch]
105 | extern YYLTYPE cflloc;
|                ^
cfparse.c:1162:9: note: type 'struct cfltype' should match type 'struct YYLTYPE'
1162 | YYLTYPE yylloc
|         ^
cfparse.c:1162:9: note: …
```

Fix redefinition of YYLTYPE struct caused by wrong include order

---

tgt-pcb/fp.y
vhdlpp/parse.y

bison 3.4.2 complains when encountering '%pure-parser':
"warning: deprecated directive, use ‘%define api.pure’"
A quick google suggests this option has been around since at least
2012, maybe longer, so probably safe to replace.
Signed-off-by: Nicholas Sielicki <sielicki@yandex.com>

replace deprecated yacc directives

---

tgt-vvp/vvp_process.c

Simulator should warn if a case statement is qualified with priorty or unique and the value is not handled.

Validate that value is  handled for case priority and unique qualifiers

---

Makefile.in

Without the dependency on `installdirs`, when running `make -j N DESTDIR=/somewhere install`, those file installation targets might run concurrently with the mkinstalldirs target, which might lead to file not found errors.
For example:
```
$ make -j24 DESTDIR=/var/tmp/portage/sci-electronics/iverilog-10.3/image install
....
mkdir -p -- /var/tmp/portage/sci-electronics/iverilog-10.3/image/usr/bin /var/tmp/portage/sci-electronics/iverilog-10.3/image/usr/include/iverilog /var/tmp/portage/sci-electronics/iverilog-10.3/image/usr/lib64/ivl /var/tmp/portage/sci-electronics/iverilog-10.3/image/usr/lib64/ivl/include /var/tmp/portage/sci-electronics/iverilog-10.3/image/usr/share/man /var/tmp/portage/sci-electronics/iverilog-10.3/image/usr/share/man/man1
/usr/bin/install: cannot create regular file …
```

Makefile.in: fix mkdir race during "make -j N install"

---

driver/cflexor.lex
driver/cfparse_misc.h
libveriuser/priv.h

See also: https://bugs.gentoo.org/706366
gcc-10 and above flipped a default from -fcommon to -fno-common: https://gcc.gnu.org/PR85678
Usually all it takes is to add a few 'extern' declarations and move definitions from header files to modules. I've port iverilog to gcc-10 accroding to this guide:
https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common
To fix this, I analyzed the code, and found ``pli_trace`` has been defined at here:
https://github.com/steveicarus/iverilog/blob/v10_3/libveriuser/priv.c#L24
So I changed ``FILE* pli_trace;`` to ``extern FILE* pli_trace;``.
The var ``current_file`` only in ``cfparse_misc.h``, I changed it from ``char *current_file;`` to ``extern char *current_file;`` and declaring it in cflexor.lex

Fix fails to build with -fno-common or gcc-10

---

netmisc.cc

Currently, if Icarus encounters chained range selections during compilation, i.e.: `assign b = a[4:0][1:0];`, it fails an assertion and crashes. I've changed this behavior to instead have a useful error message, so that the user knows what went wrong and can fix their code.

Replace assertion in evaluate_index_prefix with useful error message

---

Makefile.in
cadpli/Makefile.in
driver-vpi/Makefile.in
driver/Makefile.in
ivlpp/Makefile.in
libveriuser/Makefile.in
tgt-blif/Makefile.in
tgt-fpga/Makefile.in
tgt-null/Makefile.in
tgt-pal/Makefile.in
tgt-pcb/Makefile.in
tgt-sizer/Makefile.in
tgt-stub/Makefile.in
tgt-verilog/Makefile.in
tgt-vhdl/Makefile.in
tgt-vlog95/Makefile.in
tgt-vvp/Makefile.in
vhdlpp/Makefile.in
vpi/Makefile.in
vvp/Makefile.in

The most original detailed information is here: https://bugs.gentoo.org/705412
The original Makefile used a very unusual installation method, e.g., 
https://github.com/steveicarus/iverilog/blob/master/Makefile.in#L356
```Makefile
$(includedir)/vpi_user.h: $(srcdir)/vpi_user.h installdirs
$(INSTALL_DATA) $(srcdir)/vpi_user.h "$(DESTDIR)$(includedir)/vpi_user.h"
```
It checks $(includedir)/vpi_user.h but installed to "$(DESTDIR)$(includedir)/vpi_user.h"
If an old version of iverilog is already installed, when download a new released compressed package and decompress it, the timestamp of source code may old and when doing overwrite installation, the old file may not update due to the installed file have new timestamp.
This causes some problems, which can happen in the following cases:
- bump …

Fix iverilog files not update bug during overwrite installation

---

vvp/config.h.in

Compilation failed for me due to missing include for `malloc`.
```
x86_64-w64-mingw32-g++ -I. -I..  -DHAVE_CONFIG_H -DICARUS_VPI_CONST=const -DIVL_SUFFIX='""' -DMODULE_DIR1='"/usr/local/lib/ivl"'  -Wall -Wextra -Wshadow  -D__USE_MINGW_ANSI_STDIO=1  -g -O2 -MD -c main.cc -o main.o
In file included from main.cc:22:0:
config.h: In function 'char* strndup(const char*, size_t)':
config.h:204:33: error: 'malloc' was not declared in this scope
char*tmp = (char*)malloc(n);
```
Fix by including `cstdlib` for malloc

Add missing include for malloc

---

elaborate.cc

See this PR: https://github.com/steveicarus/ivtest/pull/15
Which adds test implicit-port7

Fix how explicitly unconnected ports are handled in the presence of .*

---

parse.y

For functions without a port list in parantheses, declarations are optional in SystemVerilog.
This is true even in IEEE1800-2005, but not in IEEE1364-2005

Fix port-list-less declaration-less functions for SystemVerilog

---

elaborate.cc

Assert is apropriate, since it's not expected that the returned value is NULL in this case.
This is a follow-up to https://github.com/steveicarus/iverilog/pull/335
Reproducing my comment there:
@martinwhitaker
Indeed, yours is a much simpler overall solution, however my gut is telling me, in addition to that to add an assert that res is not null, after the first line of this snippet:
NetNet*res = target->find_signal(target->basename());
ivl_variable_type_t lv_type = res->data_type();
This function can sometimes return NULL, and it may be true that at this point we know that we are not elaborating a void function, therefore it can't be NULL, but it's not obvious from this snippet.
Do you agree?

Add assert to protect against potentially dereferencing null pointer.

---

aclocal.m4

The aclocal.m4 called nm directly.
It can cause issue in cross-compiling and because is not possible use a different NM implementation (like llvm-nm).
The compile error log:
https://bugs.gentoo.org/attachment.cgi?id=648556
Closes: https://bugs.gentoo.org/731906

aclocal.m4: fix issue in cross-compiling

---

Makefile.in
tgt-pcb/Makefile.in
vhdlpp/Makefile.in
vvp/Makefile.in

The current bison (3.7) generates a *.cc file that includes the header
it generated. For parse.cc this would be parse.hh. Right now, we rename
this header to have a common name used in other files, but this results
in a compile error for the parse.cc file:
parse.cc:462:10: fatal error: parse.hh: No such file or directory
462 | #include "parse.hh"
|          ^~~~~~~~~~
Fix this by telling bison to output the header file to the correct
filename in the first place so that we don't have to rename it.
(using the --defines instead of -d option).
This looks like a bison specific option not available in Posix yacc;
but looks like we're requiring bison anyway.
Signed-off-by: Henner Zeller <h.zeller@acm.org>

Bison includes its generated header in *.cc. Generate with correct name.

---

parse.y

Unless explicitly declared a wire an enum output port is of variable type
and should be marked as IMPLICT_REG.
Currently this is only done when the base type of the enum is `logic`. But
it should be done for all enums regardless of their base type.
Without this change for example the following snippet
```systemverilog
typedef enum {
A,
B
} E;
module M (
input E ei,
output E eo
);
always_comb eo = ei;
endmodule
```
fails with the following error message
```
test_enum.sv:11: error: eo is not a valid l-value in M.
test_enum.sv:8:       : eo is declared here as wire.
```

parse.y: Mark enum output ports always as IMPLICT_REG

---

tgt-vvp/stmt_assign.c
vvp/codes.h
vvp/compile.cc
vvp/opcodes.txt
vvp/vthread.cc
vvp/vvp_darray.cc
vvp/vvp_darray.h
vvp/vvp_object.cc
vvp/vvp_object.h

IEEE Std 1800-2017 Section 7.6 Array assignments
Assignment of a dynamic array creates a duplicate of the source,
so that assignments to the copy don't impact the original. Handle
all sorts of dynamic array base types.
See issue #383 .

Fix dynamic array assignment to make a copy of the rvalue.

---

elab_lval.cc
elab_net.cc

When doing continuous assignment of packed structs, support the case
where the value being assigned is a member of a member, etc. Procedural
assignments already support this.
See issue #307

Support nested struct in continuous assign l-values

---

.github/workflows/test.yml

As discussed in #400, this PR updates the Windows job in GitHub Actions, in order to use Action msys2/setup-msys2 for updating the built-in MSYS2 installation, and for adding dependencies. By default, the Action caches installed packages.

ci/win: install MSYS2 packages through setup-msys2 (cached) 

---

vvp/vpi_callback.cc

Segfault occurs if a `cbNextSimTime` callback is removed. This PR adds a check and skips the callback if it was removed for the rest of the VPI callbacks.
```gdb
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x000055555564b523 in vpiNextSimTime () at vpi_callback.cc:580
#2  0x0000555555617ddd in schedule_simulate () at schedule.cc:1179
#3  0x00005555555c7c35 in main (argc=<optimized out>, argv=<optimized out>) at main.cc:465
```

Skip all removed VPI callbacks

---

mingw.txt
msys2/README.md

Coming from #398.
> I think we need documentation, somewhere, of the msys2 packaging and how to use it. The iverilog.wikia.com documentation site, and/or the iverilog.icarus.com main site?
> possibly a README in the source tree and/or documentation in the iverilog.wikia.com documentation site, showing people how to put the msys2 stuff to good use. It would be a shame if all this effort goes unused for lack of documentation.
> Feel free to update iverilog.fandom.com/wiki/Installation_using_MSYS2.
I updated the wiki:
- https://iverilog.fandom.com/wiki/Installation_using_MSYS2
- https://iverilog.fandom.com/wiki/Installation_using_MSYS2?diff=4316&oldid=4271
This PR adds a README to subdir msys2, so that users can find minimal guidelines next to the PKGBUILD file. `mingw.txt` is updated so …

doc: add MSYS2 readme

---

elab_sig.cc
netlist.cc
netlist.h
t-dll-proc.cc
t-dll.cc
tgt-stub/expression.c
vvp/event.cc
vvp/event.h

In the rare cases where DARRAY signals are in the network, handle
them by creating the proper ivl_nexus_t node. This also implements
the receive of vvp_object_t objects bu vvp_fun_anyedge_sa. This
together makes it possible for IVL_VT_DQUEUE objects to be in
wait lists.
This fixes #412

Handle dynamic queue objects in event context

---

PExpr.cc
PExpr.h
PScope.h
design_dump.cc
elab_expr.cc
elab_scope.cc
elaborate.cc
net_design.cc
net_expr.cc
net_scope.cc
netlist.h
netmisc.cc
netmisc.h
netscalar.h
nettypes.cc
nettypes.h
netvector.cc
netvector.h
parse.y
pform.cc
pform.h
pform_dump.cc
pform_types.h
symbol_search.cc
t-dll.cc

Use the common data_type_or_implicit rules to support type
definitions for parameters. This eliminates a bunch of special
rules in parse.y, and opens the door for parameters having
more complex types.

Rework parsing of parameter types

---

elab_lval.cc
elab_type.cc
parse.y
pform.cc
pform_dump.cc
pform_types.h

output ports declared like this:
..., output real out, ...
are not wires unless the net type is explicitly given. The actual fix is in parse.y, the port_declaration rule. The rest of this PR is debug code improvements.
Fixes issue #456.

output ports of real type are variables, not wires.

---

elab_expr.cc
elab_lval.cc
elab_sig.cc
net_expr.cc
netmisc.cc

This method returns the name of the enumeration, as a string. This was partially implemented, but wasn't finished at the time since string functions seemed to not work. That's OK now, so finish the implementation.
And while I'm at it, make many debug messages more uniform in format.
This fixes issue #453 .

Implement the enum.name() method

---

Makefile.in
PExpr.h
elab_expr.cc
elab_sig.cc
elaborate.cc
make_ivl_type.cc
netmisc.h
nettypes.h
pform_types.h
symbol_search.cc

This PR includes a rework of the symbol_search code, and the symbol_search() API. That function has accumulated hacks over the years, leading to a lot of ad hoc handling of things like members/methods of symbols. So I redesign the symbol_search() interface and largely reimplemented the function. It's now much cleaner and easier to read. There is also a compatibility API so that all that legacy use of symbol_search() can continue as before, but we should work towards using this new API.
This PR is still draft because I'm in the process of putting this new API to use to address issue #436. 
I'm publishing this as a draft PR so people can see what's going on here.

Queue element expressions

---

eval_tree.cc
tgt-vvp/eval_condit.c
tgt-vvp/eval_vec4.c

Section 11.4.7 of the SystemVerilog standard states
```
The && and || operators shall use short circuit evaluation as follows:
- The first operand expression shall always be evaluated.
- For &&, if the first operand value is logically false then the second operand shall not be evaluated.
- For ||, if the first operand value is logically true then the second operand shall not be evaluated.
```
vvp currently evaluates both operands of a logical operator. This works
fine as long as the right-hand side does not have a side effect. But if it has
the result might be incorrect.
E.g. for `a && b++` `b` must not be incremented if `a` evaluates to false.
The Verilog LRM mentions that it is allowed to short circuit any expression
"if the final result of an expression can be determined early". But …

Short circuit logical operator

---

lexor_keyword.gperf

I use `unique0` alot and always get the warning "value is unhandled for priority or unique case statement" when there is no default case (which there normally isn't in combination with `unique0`). I found that this is because the keyword `unique0` was mapped to the `K_unique` token instead of `K_unique0`.
I don't know if this was done intentionally to workaround another problem or if it was just a typo.

Fix unique0 keyword/token mapping

---

configure.ac
vvp/Makefile.in

Small explanation:
AX_PROG_CC_FOR_BUILD - moved from bottom to top of configure.ac, since all libraries tested for main compiler were also required in this case for native compiler, making a need of installation of zlib, bz2,... that were not used at all 
BUILDCC - previously wrong compiler was used for draw_tt, this change makes cross compile working fine.

Fix for cross compile build

---

driver/main.c

There is no /proc/self/exe on OSX, so it require a bit different code to get proper ivl_root.

Fix find_ivl_root for OSX

---

elab_sig.cc
elab_type.cc
pform.cc
pform_types.cc
pform_types.h

Currently it is only possible to declare packed array variables with a struct type as the element type. And only if the struct does not contain any atom2 or enum types.
Add support for packed arrays of other packed types. This includes packed arrays of enums and vectors as well as packed arrays of packed arrays.
Since packed arrays of packed types are already supported for class members the infrastructure for elaborating all types of packed arrays exists. It just needs to be called when elaborating a signal.
For this to work with enums and atom2 types it is also necessary to define figure_packed_base_type() for these two.
In addition this PR adds a fix to handle invalid packed dimensions correctly and report an elaboration error rather than crash when they are encountered.
Regression …

Support signals of packed arrays of packed types

---

ivtest/gold/struct_invalid_member.gold
ivtest/ivltests/struct_invalid_member.v
ivtest/regress-sv.list
ivtest/regression_report-devel.txt
ivtest/regression_report-fsv.txt
ivtest/regression_report-strict.txt
ivtest/regression_report-vlog95.txt
parse.y

When something goes wrong when parsing a struct member, e.g. the type does
not exist, a nullptr is added to the struct member list. This will cause a
crash when iterating over the list.
E.g.
```
logc x;
} s;
```
Add a check so that nullptr members are not added to the list.

Handle invalid struct members

---

ivtest/ivltests/enum_in_class.v
ivtest/ivltests/enum_in_class_name_coll.v
ivtest/ivltests/enum_in_struct.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
ivtest/regression_report-devel.txt
ivtest/regression_report-fsv.txt
ivtest/regression_report-strict.txt
ivtest/regression_report-vlog95.txt
parse.y
pform.cc
pform.h
pform_pclass.cc

When creating an enum type it must be added to the scope where it is
declared so it can later be elaborated and the enum and its names can
be referenced in expressions.
In addition the names of the enum must be added to the lexor scope so that
name collisions are detected and can be reported as errors.
This is done with pform_put_enum_type_in_scope() function.
At the moment the function is called from two different places
* When adding a typedef of a enum type
* When creating a signal of a enum type
In addition the enum_type_t is added to a class scope `enum_sets` when
declaring a enum property in a class. But this only makes sure that the
enum gets elaborated, its names are not added to the lexor scope.
This works fine for the most part, but breaks for a few corner cases.
E.g. it is …

 Put enum type into scope when declaring it

---

ivtest/ivltests/array_packed.v
parse.y

Add support for two more cases where packed arrays are allowed.
1) Direct packed arrays of structs and enums without a typedef of the struct or enum
E.g.
```systemverilog
int x;
} [1:0] pa;
```
2) Using a scoped type identifier as the base type for the packed array
E.g.
```systemverilog
package p;
typedef logic [1:0] vector;
endpackage
module test;
p::vector [1:0] pa;
endmodule
```
Both is already supported just fine during elaboration, just needs some minor changes to the parser to support this.

Support direct packed arrays of struct and enums and packed arrays of scoped types

---

elab_type.cc
ivtest/ivltests/struct_signed.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
ivtest/regression_report-devel.txt
ivtest/regression_report-fsv.txt
ivtest/regression_report-strict.txt
ivtest/regression_report-vlog95.txt
netstruct.h
parse.y
pform_types.h

packed structs and packed unions as a whole can either be signed or
unsigned. This information is used when it is used as a primary in an
expression, i.e. without accessing any of the members. E.g.
```systemverilog
struct packed signed {
logic [15:0] x;
} signed_struct;
```
Add support for parsing and elaborating signed structs as well as a test that verifies that signed structs work as expected.

Add  support for signed packed structs/unions 

---

PExpr.h
dup_expr.cc
elab_expr.cc
ivtest/ivltests/br_gh130b.v
ivtest/ivltests/br_gh386d.v
ivtest/ivltests/sv_cast_packed_array.v
ivtest/ivltests/sv_cast_packed_struct.v
ivtest/regress-fsv.list
ivtest/regress-ivl1.list
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_expr.cc
net_scope.cc
netlist.h
netmisc.h
pad_to_width.cc

Currently explicit casts for packed types are only supported to atom2 and vector types. Generalize this code so that it supports cast to all packed types.
Correctly supporting explicit cast to enum is a bit more involved. Enum variables can only be assigned a value if the value is of the same enumeration type as the variable. Explicitly casting an expression to a enumeration type allows to assign it to an enum variable, even if the original type of the expression was not of that enumeration type.
In order to support this the type of the cast needs to be attached to the expression, so that the check in the assignment elaboration can verify the type.

Add support for explicit cast to packed array, packed struct and enum

---

PExpr.cc
PScope.h
elab_scope.cc
ivtest/ivltests/enum_order.v
ivtest/regress-sv.list
pform.cc
pform_dump.cc

enums for a scope are stored in a std::set. This means when iterating over
the enums during elaboration it is possible that they are elaborated in a
different order than they have been declared in. This causes problems if
one enum references items of the other enum. E.g.
```systemverilog
enum {
A
} a;
enum {
B = A
} b;
```
In the current implementation whether this works or not depends on the
pointer values of the enum_type_t for `a` and `b`, which can change between
environments.
To make sure that enums are always elaborated in the same order use a std::vector
instead of a std::set.

 Elaborate enums in the order they have been declared 

---

ivtest/ivltests/unnamed_block_var_decl.v
ivtest/regress-fsv.list
ivtest/regress-vlg.list
parse.y

While it is not a particular useful construct it is legal to have a
begin/end block with just variable declarations and no statements. E.g.
```systemverilog
begin
int x;
end
```
At the moment there is a special rule for completely empty begin/end
blocks. Remove that rule and change the statement_or_null_list in the
begin/end block parser section to a statement_or_null_list_opt. This way it
covers both completely empty blocks as well as blocks with only variable
declarations.
Note that this already works as expected for named begin/end blocks

 Allow unnamed begin/end block with only variable declarations

---

elab_scope.cc
elab_type.cc
ivtest/gold/enum_line_info.gold
ivtest/gold/struct_line_info.gold
ivtest/ivltests/enum_line_info.v
ivtest/ivltests/struct_line_info.v
ivtest/regress-sv.list
pform.cc
pform_types.h

Both `netenum_t` and and `netstruct_t` inherit from `LineInfo`. This information is used when generating error messages relating to these types. But the line info is not always set correctly, which can result in confusing error messages. E.g.
```
:0: error: Member r of packed struct/union must be packed.
```
For structs the line info is never set.
For enums the line info is set to the location where a signal of that type is declared. This works OK when it is a direction enum signal declaration since the declaration location of the signal and the type are the same. But if the enum is declared inside an aggregate type such as a class or struct it is never set. If the enum is a typedef it will be set to the location of the last signal declaration using that type.
Set the LineInfo for both of …

Set correct line info for enums and structs

---

ivtest/ivltests/localparam_implicit.v
ivtest/regress-sv.list
parse.y
pform.cc
pform.h

When declaring module parameters in the ANSI style parameter list it is
possible to omit the `parameter` or `localparam` keyword. In this case
whether the parameter is local or non-local is inherited from the previous
parameter.
In the current implementation when the type of the parameter is not
specified it will always use parameter. E.g. the following will create a
localparam A and a parameter B, while it should be localparam A and B.
```systemverilog
module #(localparam A = 1, B = 2);
```
Fix this by remembering whether the previous entry was a parameter or
localparam. This is similar to how the parameter data type is already
remembered.
To enable this the handling of parameters and localparams is consolidated. This allows Verilog-AMS parameter value ranges to be specified on …

 Handle implicit `localparam`

---

elab_scope.cc
ivtest/gold/br_gh157.gold
ivtest/gold/parameter_invalid_override.gold
ivtest/gold/pr498b.gold
ivtest/ivltests/parameter_invalid_override.v
ivtest/ivltests/pr498a.v
ivtest/ivltests/pr498b.v
ivtest/regress-ivl1.list
ivtest/regress-sv.list
ivtest/regress-vlg.list
net_design.cc
net_scope.cc
netlist.h

Overriding a parameter that does not exist will only generate a warning at
the moment. This can hide programming mistakes such as an typo in a
parameter override.
There is nothing in the LRMs to support that this should only be warning,
so elevate this to an error. This is consistent with how an error is
generated when trying to reference a non-existing port or variable.
The generated error message differentiates between whether the parameter
does not exist at all, or whether it is a localparam.
There are two regression tests that rely on that only a warning is
generated, these have been updated to expect an error.

 Report error when trying to override non-existing parameter

---

ivtest/ivltests/localparam_implicit2.v
ivtest/regress-sv.list

The localparam_implicit.v test was broken by a recent commit. Fix the test, since the commit is correct and the test really is broken.

Fix localparam_implicit.v test

---

ivtest/ivltests/unnamed_fork_var_decl.v
ivtest/regress-fsv.list
ivtest/regress-vlg.list
parse.y

While it is not a particular useful construct it is legal to have
parallel blocks with just variable declarations and no statements. E.g.
```SystemVerilog
fork
int x;
join
```
At the moment there is a special rule for completely empty parallel
blocks. Remove that rule and change the statement_or_null_list in the
fork/join parser section to a statement_or_null_list_opt. This way it
covers both completely empty parallel blocks as well as parallel blocks
with only variable declarations.
Note that this already works as expected for named parallel blocks.
This is similar to https://github.com/steveicarus/iverilog/pull/594 which made the same change for sequential blocks.

Allow unnamed parallel block with only variable declarations

---

elab_scope.cc
ivtest/ivltests/sv_class_extends_scoped.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y

A base class can be referenced by scope. E.g. if the base class is in a
package.
```SystemVerilog
package P;
class B;
endclass
endpackage
module test;
class C extends P::B;
endlcass
endmodule
```
To support this let the parser accept a scope identifier for the base
class.
A small change is also necessary to how the base class lockup is done
during elaboration. At the moment the code will search for the base class
by name in the current scope. This doesn't work with scoped identifiers.
But we already have a reference to the base class data type, so we don't
have to search for it by name.
To enable this add a shared parser rule that handles both type identifiers and scoped type identifiers.

 Support scoped base class type

---

ivtest/gold/sv_end_label_fail.gold
ivtest/gold/sv_end_labels_bad.gold
ivtest/gold/sv_end_labels_unnamed.gold
ivtest/ivltests/sv_end_labels_unnamed.v
ivtest/regress-sv.list
parse.y

Currently when encountering an end label on a unnamed block
a 'syntax error' will be generated and the parser will give up.
Slightly refactor the parser so that this case is detected, a more specific
error message is generated and the parser can recover and continue.
This also slightly reduces the parser since it allows to merge the almost
identical rules for handling named and unnamed blocks.
To make this easier to implement add a common helper function that will
handle the end label checking. This helper function will emit consistent
error messages for the different types of end labels, which requires
refreshing of some test gold files.

 Let the parser recover from end label on unnamed block

---

PExpr.cc
PScope.h
elab_scope.cc
elaborate.cc
ivtest/ivltests/parameter_in_generate1.v
ivtest/ivltests/parameter_in_generate2.v
ivtest/regress-fsv.list
ivtest/regress-sv.list
ivtest/regress-vlg.list
net_scope.cc
netlist.h
pform.cc
pform_dump.cc

SystemVerilog allows to use the `parameter` keyword in a generate
block. If used in a generate block it behaves like a `localparam` and
cannot be overridden.
This is described in section 27.2 ("Generate constructs - Overview") of the
LRM (1800-2017).
To be able to generate better error messages when trying to override such
a parameter track whether the parameter is overridable rather than converting
it to localparam.
Also keep parameters and localparams in the same list during parsing to
reduce some duplicated code.

Allow parameter in generate blocks for SystemVerilog

---

ivtest/ivltests/localparam_implicit3.v
ivtest/ivltests/parameter_omit1.v
ivtest/ivltests/parameter_omit2.v
ivtest/ivltests/parameter_omit3.v
ivtest/ivltests/parameter_omit_invalid1.v
ivtest/ivltests/parameter_omit_invalid2.v
ivtest/ivltests/parameter_omit_invalid3.v
ivtest/regress-fsv.list
ivtest/regress-sv.list
ivtest/regress-vlg.list
parse.y
parse_misc.h
pform.cc
pform.h

SystemVerilog allows to completely omit the `parameter` keyword in a
module parameter port list. This is described in section 6.20.1 ("Parameter
declaration syntax") of the LRM (1800-2017).
E.g.
```SystemVerilog
module a #(X = 10) ...
module b #(int Y = 20) ...
```
It also allows to redefine the parameter type without having to have a
`parameter` or `localparam` before the type.
E.g.
```SystemVerilog
module a #(parameter int A = 1, real B = 2.0) ...
module b #(int X = 3, real Y = 4.0) ...
```
Extend the parser to support this.
Note that it is not possible to declare a parameter with an implicit data
type this way.
E.g. the following is not legal SystemVerilog
```SystemVerilog
module a #([3:0] A = 1) ...
module b #(int X = 2, signed Y = 3.0) ...
```
There are a few places where the parser …

 Allow omitting `parameter` in module parameter port list 

---

elab_expr.cc
ivtest/ivltests/bits3.v
ivtest/regress-sv.list
parse.y

The `$bits()` system function can be called with a data type.
At the moment only calling it with a typedef data type is supported,
but not built-in data types. E.g.
* `typedef int T; ... $bits(T)` works
* `$bits(int)` does not work
Add support for being able to pass all data types to `$bits()` by
allowing `data_type` to appear in a primary expression in the parser.
Also correctly handle unpacked array data types by taking
the unpacked dimensions into account.

Support calling $bits() with built-in data types

---

Module.cc
Module.h
ivtest/ivltests/parameter_no_default.v
ivtest/ivltests/parameter_no_default_fail1.v
ivtest/ivltests/parameter_no_default_fail2.v
ivtest/ivltests/parameter_no_default_toplvl.v
ivtest/regress-fsv.list
ivtest/regress-sv.list
ivtest/regress-vlg.list
main.cc
net_design.cc
parse.y
pform.cc
pform.h
pform_dump.cc

SystemVerilog allows to omit the default value of a parameter declared in a
parameter port list. In this case the parameter must be overridden for
every module instance. This is defined in section 6.20.1 ("Parameter
declaration syntax") of the LRM (1800-2017).
In addition a module that has a parameter without a default value does not
qualify for automatic toplevel module selection.

Support parameters without default value

---

ivtest/ivltests/l_impl.v
ivtest/regress-sv.list
lexor.lex
parse.y
tgt-vvp/eval_vec4.c

Implement the logical implication "->" operator for vec4 types, and also fix up some ugly shift/reduce conflicts that the operator brings on.

Logical implication

---

parse.y

Is there interest in ensuring features like this are properly restricted to SystemVerilog? I've seen that there is some inconsistency here, so I'm curious what the desired behavior is.

Restrict edge event to SV

---

ivtest/ivltests/generate_module.v
ivtest/ivltests/generate_specify.v
ivtest/ivltests/generate_specparam.v
ivtest/ivltests/generate_timeunit.v
ivtest/regress-sv.list
ivtest/regress-vlg.list
parse.y
pform.cc
pform.h

Most things that can be declared in a module can also be declared in a
generate block.
But there are a few exceptions that can not be declared in generate block
* module, program or interface declaration
* specify block or specparam
* timeunit
Some of these currently work while some of them trigger an assertion and
cause and application crash.
Add checks to make sure that all of them these are reported as an error and
do not cause a crash.

Generate error for invalid declarations within generate block 

---

ivtest/ivltests/sv_class_new_init.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y
pform.cc
pform.h
pform_struct_type.cc

Currently there are a couple of different but similar functions and parser rules
that are used for declaring nets and variables. Consolidate these functions
and parsing rules where possible to remove some duplicated code.
A side effect of this refactoring is that class new statements can be used
as variable initializers as allowed by the standard. E.g.
```SystemVerilog
module test;
class C;
endlcass
C c = new C;
endmodule
```
This previously was not supported for block item variable declarations, but only for class and package properties.

Consolidate signal declaration

---

PExpr.h
elab_expr.cc
elab_scope.cc
ivtest/ivltests/enum_in_class.v
ivtest/ivltests/sv_class_localparam.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_expr.cc
net_scope.cc
netclass.cc
netclass.h
netlist.cc
netlist.h
parse.y
pform.cc
pform.h
pform_pclass.cc

SystemVerilog allows `parameter` and `localparam` to declare constants
within a class scope.  E.g.
```SystemVerilog
class C;
localparam A = 10;
endclass
```
In this context both declare a local parameter that can not be overwritten.
Parameters that have been declared in a class scope can also be accessed
via a object of the class type. E.g.
```SystemVerilog
class C;
localparam A = 10;
endclass
initial begin
C c = new
$display(c.A);
end
```
Supporting this requires a bit of refactoring of the parameter elaboration
code to work with a const NetScope* since the class_type_t only allows
const access to the scope.

Support non-overridable parameters in classes

---

vvp/stop.cc
vvp/vpi_priv.cc
vvp/vpi_priv.h

Several scope types were not understood by the push command, and
a few types were not displayed reasonably. Flesh these out.
This resolves #622.

Add more types to vvp-stop

---

ivtest/ivltests/module_output_port_sv_var1.v
ivtest/ivltests/module_output_port_sv_var2.v
ivtest/ivltests/module_output_port_var1.v
ivtest/ivltests/module_output_port_var2.v
ivtest/regress-sv.list
ivtest/regress-vlg.list
ivtest/regress-vlog95.list
parse.y
pform.cc

In SystemVerilog output ports are a variable if either:
* They are explicitly declared a variable (with the `var` keyword)
* There is no explicit net type, but a explicit data type
This is in detail described in section 23.2.2.3 ("Rules for determining port
kind, data type, and direction") of the LRM (1800-2017).
E.g.
```systemverilog
output x // Net
output [1:0] x // Net
output signed x // Net
output wire x // Net
output wire logic x // Net
output var x // Variable
output logic x // Variable
output var logic x // Variable
output int x // Variable
output real x // Variable
output string x // Variable
output some_typedef x // Variable
```
At the moment the code checks for certain data types and only makes the
output port a variable for those. And it is even different data types
depending …

 Make output ports with data type variables

---

elab_scope.cc
ivtest/ivltests/issue576.v
ivtest/regress-sv.list
netlist.cc
netlist.h

This fixes the assertion failure that happens when void functions are used in always_comp functions. This fixes #576, but does not address the problem of the contents of a void function not being scanned for sensitivity lists.

Always comb vs void func

---

eval_tree.cc

Consistently use ivl_assert() instead of assert() in the eval_tree()
implementations. ivl_assert() includes information about which expression
triggered the assert and it makes debugging easier.

eval_tree: Use ivl_assert() instead of assert()

---

elab_sig.cc
ivtest/gold/pr2976242c.gold
ivtest/ivltests/module_inout_port_type.v
ivtest/ivltests/module_input_port_type.v
ivtest/ivltests/net_class_fail.v
ivtest/ivltests/net_darray_fail.v
ivtest/ivltests/net_queue_fail.v
ivtest/ivltests/net_string_fail.v
ivtest/regress-fsv.list
ivtest/regress-sv.list
ivtest/regress-vlg.list
parse.y
pform.cc
pform.h
pform_types.h

While a variable can have any data type the data type for nets is quite
restricted.
The SystemVerilog LRM section 6.7.1 ("Net declarations with built-in net
types") requires that the data type of a wire is either a 4-state packed or
a unpacked struct or unpacked array of 4-state packed types.
As an extension to this iverilog allows real data type for wires as well as
2-state packed types.
Add a check that reports an error if a net with any other type is declared.
In addition in Verilog a net can not have an explicit data type at all. It
can only have a packed dimension and a signed flag. As an extension to this
Icarus also allows wires to be of `real` data type.
Note that in Verilog mode the data type is checked in the parser since only
the parser knows whether the data type is an …

Correctly handle data types on nets

---

PWire.cc
PWire.h
elab_sig.cc
ivtest/ivltests/package_vec_part_select.v
ivtest/regress-sv.list
netvector.cc
netvector.h
pform_dump.cc
tgt-vlog95/scope.c

The logic that decides whether a vector is scalar or not incorrectly flags
all variables that are declared in packages as scalar. As a result it is
not possible to do a part select on a vector declared in a package.
Rather than having an independent scalar flag consider a vector as scalar
if it does not have any packed dimensions.
Also in the PR is a small fix for the vlog95 backend to correctly generate
initializers for variables declared in packages. This is required for the new
regression test to pass with the vlog95 backend.

Fix part select on variables declared in packages

---

ivtest/ivltests/sv_string7.v
ivtest/ivltests/sv_string7b.v
ivtest/regress-sv.list
verinum.cc
vvp/vthread.cc

Fix handling of string literals as they find their way into the vvp string value stack. This bug caused string assignment to not work properly. The pertinent section of the standard is "_IEEE Std 1800-2017: 5.9.1 Special characters in strings_".
Include the sv_string7.v test to verify that this new behavior is correct.
This PR fixes issue#597

String special characters

---

vpi/sys_fst.c
vpi/sys_vcd.c

Added "-no-date" option toVPI  vcd and fst dumper to make them reproducible.

Add option to skip writing date to output file

---

ivtest/ivltests/sv_class_empty_item.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y

The SystemVerilog grammar explicitly allows an empty class item
declaration. The empty class item declaration is just a semicolon and has
no effect.
E.g. the following is legal
```SystemVerilog
class C
int x;;;
endclass
```
Add support to the parser to accept empty class item declarations.

Handle empty class item declarations in parser

---

parse.y
pform.cc
pform.h

Currently there is a mix of passing line information either as `struct vlltype`
or as a separate `const char *file` and `unsigned lineno`.
For consistency always use the struct vlltype variant.

parser: Consistently pass line information as `vlltype`

---

elab_sig.cc
ivtest/ivltests/module_port_range_mismatch.v
ivtest/ivltests/task_port_range_mismatch.v
ivtest/regress-vlg.list

When using non-ANSI style port declarations it is possible to have both a
port and net or variable declaration for the same signal. In this case the
range specification for the two declarations have to match.
In the current implementation if the range specifications do not match an
error is reported and no signal is created. This generates follow up errors
about the signal not being declared when it is used.
In some cases it even causes the application to crash. E.g. the task
elaboration expects the port signal to exist. If it does not it will crash.
To avoid this still create the signal, even when an error is detected. Use
the range specification of the net or variable in this case. Overall
elaboration will still fail due to the error, but the application will not
crash.

Recover from port and signal vector range mismatch 

---

elab_scope.cc
elab_type.cc
netclass.cc
netclass.h
pform_types.h

For some data types the value returned by the `elaborate_type()` method is
shared among different signals of that type. E.g. all string or real types
get elaborated to the same ivl_type_s. This means the returned value must
not be modified, otherwise the data type for unrelated signals might get
changed.
To enforce this and protect against accidental breakage make the return type
type of the `elaborate_type()` and the related `elaborate_type_raw()`
methods const.
Note that `ivl_type_t` is used for the new return type which is a typedef
for `const ivl_type_s*`.

data_type_t::elaborate_type(): Make return type const

---

ivtest/ivltests/udp_output_reg.v
ivtest/regress-vlg.list
parse.y

The parser currently expects `reg output` for UDP registered output. But
the correct syntax is `output reg`. Fix this to accept the correct syntax.

 parser: Fix UDP registered output syntax 

---

elab_scope.cc
ivtest/ivltests/enum_compatibility1.v
ivtest/ivltests/enum_compatibility2.v
ivtest/ivltests/enum_compatibility3.v
ivtest/ivltests/enum_compatibility_fail.v
ivtest/regress-sv.list
netenum.cc
netenum.h

An enum data type declared in a module is not compatible between different
instances of the module. The type is unique in each hierarchical instance
scope. The type can for example depend on module parameters which would
result in conflicting definitions. This is defined in section 6.22 ("Type
compatibility") of the LRM (1800-2017).
At the moment enum compatibility is checked by comparing the enum_type_t.
But the enum_type_t is shared among the netenum_t that are created for each
module instance and gives the wrong result.
Since there is exactly one netenum_t created for each enum and each
instantiated scope use this to check if the data type of two enum type
signals is compatible.

Restrict enum compatibility to the same scope

---

elab_scope.cc
elab_type.cc
ivtest/ivltests/sv_class_in_module_decl.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
netclass.cc
netclass.h

For classes declared inside a module each module instance creates a new
unique class type. These types are not compatible to each other. This is
necessary since module parameters can change the class implementation.
This is defined in section 6.22 ("Type compatibility") of the LRM (1800-2017).
In the current implementation when a class is elaborated the elaborated
type is stored in the class_type_t so it is possible to look up the
elaborated class type. But this class_type_t is shared among elaborated
class types. As a result when creating multiple instances of a module with
a class definition an internal assert is triggered.
To support multiple module instances with class definitions instead of
storing the elaborated type in the type definition look up the type in the
scope in which the …

Handle multiple instances of modules with class definitions

---

elab_sig.cc
ivtest/ivltests/sv_typedef_array_base1.v
ivtest/ivltests/sv_typedef_array_base2.v
ivtest/ivltests/sv_typedef_array_base3.v
ivtest/ivltests/sv_typedef_array_base4.v
ivtest/ivltests/sv_typedef_darray_base1.v
ivtest/ivltests/sv_typedef_darray_base2.v
ivtest/ivltests/sv_typedef_darray_base3.v
ivtest/ivltests/sv_typedef_darray_base4.v
ivtest/ivltests/sv_typedef_queue_base1.v
ivtest/ivltests/sv_typedef_queue_base2.v
ivtest/ivltests/sv_typedef_queue_base3.v
ivtest/ivltests/sv_typedef_queue_base4.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

The base type of an array type needs to be elaborated in the scope where
the array type is declared. At the moment it is elaborated in the scope
where the signal is declared, which can cause incorrect results.
E.g. in the example below the width of the array base type would be 4
instead of 8.
```SystemVerilog
localparam A = 8;
typedef reg [A-1:0] T[1:0];
module test;
localparam A = 4;
T x;
endmodule
```
If an unpacked array type is specified use the scope of the array type as
the default scope for the base type. Note that the base type can still be a
typedef in a different scope than the array scope, but we need to start
searching for it in the array scope.

Elaborate base type of array types in the right scope

---

ivtest/ivltests/sv_class_constructor1.v
ivtest/ivltests/sv_class_constructor_fail.v
ivtest/ivltests/sv_class_super1.v
ivtest/ivltests/sv_class_super2.v
ivtest/ivltests/sv_class_task1.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y

A few small improvements to the parser to handle class syntax related to constructors and implicit class handles (`this`, `super`).
- Don't allow non-ANSI ports on class constructors
- Allow class constructor declaration without parenthesis after the `new`
- Allow `super` class constructor invocation without parenthesis after the `new`
- Allow to invoke class task without parenthesis after the task name when using `super` or `this` as part of the identifier path
To support this add a few parser helper rules to handle common syntax.

Small class syntax improvements

---

ivtest/ivltests/sv_package_implicit_var1.v
ivtest/ivltests/sv_package_implicit_var2.v
ivtest/regress-sv.list
parse.y

Variable declarations in packages need an explicit data type. Omitting the
data type or using just packed dimensions is not valid syntax. E.g. the
following should not work.
```SystemVerilog
package P;
x;
[1:0] y;
endpackage
```
The current implementation does accept this tough. To fix this update the
parser to only allow explicit data types for package variable declarations.

Require explicit data type for package variable declarations

---

Documentation/usage/getting_started.rst
Documentation/usage/simulation.rst

Code-block defaults created some funny highlighting for verilog.
Used ".. code-block:: verilog" directive to fix (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block)
systemverilog is also available (https://pygments.org/docs/lexers/#lexers-for-hardware-descriptor-languages)

Fix verilog formatting in usage docs code-blocks

---

elab_lval.cc
ivtest/ivltests/sv_class_static_prop1.v
ivtest/ivltests/sv_class_static_prop2.v
ivtest/ivltests/sv_class_static_prop3.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

Assigning a value to a static class property in a class task or function
will currently not write to the static signal, but instead to an otherwise
invisible per instance property. E.g. the example below will print 0 when
the task `t` is called.
```SystemVerilog
class C;
static int i;
task t;
i = 10;
$display(i);
end
endclass
```
Since static class properties are implemented as normal signals just
fallback to the default signal handling when an assignment to a static
class property is detected.

Handle assignment to static class properties in class methods

---

elab_sig.cc
ivtest/ivltests/vams_abs3.v
ivtest/regress-vams.list
ivtest/regress-vlog95.list
netlist.cc
netscalar.h
nettypes.cc
nettypes.h
pform.cc
pform_disciplines.cc

Currently a `vector_type_t` with the base type set to `IVL_VT_REAL` is used as
the data type for real type signals. But there is also the `real_type_t` data
type, which is used as the data type for function return types and class
properties.
Move signals also over to using `real_type_t`. This ensures consistent
behavior between all sorts of constructs with a data type, makes sure that
`vector_type_t` is only used for vector types.
It also allows to eventually differentiate between `real` and `shortreal`
at the elaboration stage. Currently this information is discarded by the
parser.
As a side effect this PR also fixes the rather obscure case of passing a call
to a function with a real return type as the argument to the Verilog AMS
`abs()` function.

Use `real_type_t` as the data type for `real` type signals

---

PExpr.h
Statement.h
elab_expr.cc
elaborate.cc
ivtest/ivltests/enum_method_signed1.v
ivtest/ivltests/enum_method_signed2.v
ivtest/ivltests/enum_method_signed3.v
ivtest/ivltests/enum_method_signed4.v
ivtest/ivltests/sv_class_method_signed1.v
ivtest/ivltests/sv_class_method_signed2.v
ivtest/ivltests/sv_class_property_signed1.v
ivtest/ivltests/sv_class_property_signed2.v
ivtest/ivltests/sv_class_property_signed3.v
ivtest/ivltests/sv_class_property_signed4.v
ivtest/ivltests/sv_queue_method_signed1.v
ivtest/ivltests/sv_queue_method_signed2.v
ivtest/ivltests/sv_queue_method_signed3.v
ivtest/ivltests/sv_queue_method_signed4.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_expr.cc
netlist.cc
netlist.h

The result for the built-in methods for the SystemVerilog types is
currently always unsigned. This can lead to incorrect behavior if the value
is sign extended or passed as an argument to a system function (e.g.
`$display`).
E.g. the following will print `4294967295` rather than `-1`.
```SystemVerilog
int q[$];
q.push_back(-1);
$display(q.pop_front());
```
To correctly support this consistently assign the actual data type of the
built-in method's return value to the `NetESFunc`, rather than just the width
and base type. The width, base type and also the signedness can be derived
from the data type.
The signedness of an expression can also change depending on its context.
E.g. for an arithmetic operation with one unsigned operand all operands are
treated as unsigned.
In addition to methods …

Handle signedness and width expansion for class properties and methods

---

elab_scope.cc
elab_type.cc
ivtest/ivltests/sv_queue_function.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
libmisc/LineInfo.cc
libmisc/LineInfo.h
netmisc.cc
pform_pclass.cc
pform_types.h

Currently the elaboration function for unpacked array types prints an error
for queues that they are not allowed inside classes. And while this error
gets triggered when declaring a property with a queue type, it also gets
triggered for other places that uses a queue type, e.g. a function return
type. The only exception is signals which uses a different internal code
path when elaborating queue types.
Move the error message, that is class property specific, to the class
property elaboration. This also makes sure that the error messages
references the line where the property is declared and not the line where
the type is declared.
In addition there is currently a restriction that implicit cast between
queue and dynamic array only works when the r-value is a signal.
Expand this so that the …

Allow queues as return types for functions

---

elab_expr.cc
elaborate.cc
ivtest/ivltests/sv_assign_pattern_cast.v
ivtest/ivltests/sv_assign_pattern_concat.v
ivtest/ivltests/sv_assign_pattern_const.v
ivtest/ivltests/sv_assign_pattern_expand.v
ivtest/ivltests/sv_assign_pattern_func.v
ivtest/ivltests/sv_assign_pattern_op.v
ivtest/ivltests/sv_assign_pattern_part.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
netmisc.h
tgt-vvp/stmt_assign.c

The expressions within an array assignment pattern should be evaluated in a
context that is equivalent to an assignment to a variable of the element
type of the l-value array.
This is defined in section 10.9.1 ("Array assignment patterns") of the LRM
(1800-2017).
At the moment the values in an assignment pattern are evaluated in a self
determined context, which can lead to incorrect behavior.
Use the existing `elaborate_rval_expr()` function, which is meant for
elaborating assignments, to elaborate the assignment pattern values.
This solves the following issues:
* implicit width conversion (including sign extension)
* implicit type conversion (e.g. real to vector)
* math operators that depend on the target width (e.g. addition)
* use of expressions that require `test_width()` to be …

Elaborate array assignment pattern values in the right context

---

pform.cc
pform.h

The `pform_set_param_from_type()` function is not used. The last user was
removed in commit 16646c547cbf ("Rework parsing of parameter types").
Remove the function itself.

Remove unused function `pform_set_param_from_type()`

---

parse.y
pform.cc
pform.h
pform_disciplines.cc

A small set of cleanups for the `pform_makewire()` function
- Remove unused parameters
- `pform_set_reg_idx()` is always called in combination with `pform_makewire()`. Move it into it.

Small cleanups for `pform_makewire()`

---

parse.y
pform.cc
pform.h
pform_disciplines.cc

There are a few places in the parser where a signal is created and then
immediately afterwards the signal is looked up by name to make some changes to
the signal.
Refactor the code so that the pointer to the signal is retained and the look-up
by name is no longer necessary.

Avoid signal look-up by name in the parser

---

ivtest/ivltests/module_port_shortreal.v
ivtest/regress-ivl1.list
ivtest/regress-vlog95.list
pform.cc

Currently there is a restriction in the parser that rejects `shortreal`
typed module ports. And while at the moment `shortreal` signals are
implemented as `real` typed signals, which is not standard compliant, there
is nothing special about module ports in this regard.
Note that support for `shortreal` (and `real`) nets is an Icarus extension, but ports can
also be variables, in which case a shortreal port is allowed by the LRM.
`shortreal` variables and nets are allowed everywhere else. There is no
good reason to not allow them for module ports, so remove the restriction.

Allow shortreal module ports

---

elab_expr.cc
ivtest/ivltests/sv_cast_typedef.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

PECastType currently uses the unelaborated data type to make the decision
how to implement the cast. The unelaborated data type is provided by the
parser and this works as long as the parser knows the data type.
But for example with type parameters the actual data type is not known
until elaboration. In preparation for supporting type parameters make sure
to only use the elaborated type in the PECastType implementation.

PECastType: Use elaborated data type

---

design_dump.cc
ivtest/ivltests/br_gh699.v
ivtest/regress-sv.list
net_func_eval.cc

When the r-value to an assignment fails to elaborate, and that r-value is a function, the NetAssign::evaluate_function segfaults. Fix the segfault by properly returning an error flag. It is not necessary to count an error, since the elaboration failure in the first place counted the error.
Also add the test from Issue#699.
This fixes #699 .

Fix issue 699: segfault when rvalue to elaboration fails.

---

parse.y
pform.cc
pform.h
pform_types.h

The lgate struct has its own fields for tracking file and line number,
while everything else that has this information attached inherits from the
LineInfo class.
Make lgate also inherit from LineInfo for consistency.

lgate: Inherit from LineInfo

---

elab_expr.cc
ivtest/ivltests/sv_class_new_fail1.v
ivtest/ivltests/sv_class_new_fail2.v
ivtest/regress-sv.list

Using a class new operator on a non-class variable should result in an
error. At the moment when using a class new operator on a dynamic array or
queue will result in an segmentation fault. This is because the
implementation assumes that the left hand side is of a class type.
Add a check in the class new operator implementation that the type of the
left hand side is a class. Report an error if it is not.

 Handle class new assignment to non-class variables

---

elab_type.cc
ivtest/ivltests/parameter_1bit.v
ivtest/ivltests/parameter_scalar.v
ivtest/regress-sv.list
ivtest/regress-vlg.list
net_design.cc
netvector.cc
netvector.h

Parameters without any type or range specification inherit the type from
the value that has been assigned to it. Similarly a parameter with just an
`signed` or `unsigned` keyword will inherit its range from the value
assigned to it.
In the current implementation any vector type parameter that does not have
a range specification inherits the type form the assigned value. That
includes parameters with an explicit scalar vector type. E.g.
```SystemVerilog
parameter bit X = 10
```
Make sure that a parameter only uses the width from the assigned value if
the parameter does not have an explicit data type.
To support this we need to remember whether a `netvector_t` was declared as
an explicit or implicit data type. Currently this information is only
available on the unelaborated `vector_type_t`.

Handle scalar typed parameters

---

ivtest/ivltests/real_array_multi_dim.v
ivtest/regress-vlg.list
ivtest/regress-vlog95.list
tgt-vvp/stmt_assign.c

There is currently a restriction in the vvp code generator backend that
throws an assertion when generating write access for a multi-dimensional
real array.
But there is nothing special about multi-dimensional arrays. In vvp arrays
are in canonical form. Meaning they only have a single dimension and the
conversion form multi to single dimension is done in the higher layers.
Remove the assert to allow multi-dimensional real arrays.

tgt-vvp: Allow multi-dimensional real arrays

---

ivtest/ivltests/sv_darray_oob_real.v
ivtest/ivltests/sv_darray_oob_string.v
ivtest/ivltests/sv_darray_oob_vec2.v
ivtest/ivltests/sv_darray_oob_vec4.v
ivtest/ivltests/sv_queue_oob_real.v
ivtest/ivltests/sv_queue_oob_string.v
ivtest/ivltests/sv_queue_oob_vec2.v
ivtest/ivltests/sv_queue_oob_vec4.v
ivtest/regress-fsv.list
ivtest/regress-sv.list
ivtest/regress-vlog95.list
netdarray.h
netqueue.h

Commit e1870acfacc9 ("Return the correct value when a queue or darray
references an undefined element") added support for specifying the width of
the vector elements stored in a queue or dynamic array, so that an
out-of-bounds access can create a word with the right width.
To get the element width of a queue or dynamic array it uses the
`packed_width()` method. But this method is only implemented for
`netqueue_t` and returns always 1 for dynamic arrays. As a result
out-of-bounds access on a dynamic array will push a vector of the wrong
width onto the stack if the vector element is wider than 1 bit. This will
usually trigger an assert in vvp.
Fix this by moving the `packed_width()` method implementation from
`netqueue_t` to its base class `netdarray_t` so that it works for all types
of …

Return value of correct width for dynamic array out-of-bound access

---

ivtest/gold/array_dump.vcd.gold
ivtest/gold/br_gh156.vcd.gold
ivtest/gold/pr2859628.vcd.gold
ivtest/gold/vcd-dup.vcd.gold
ivtest/ivltests/br_gh156.v
ivtest/regress-vlg.list
vpi/sys_fst.c
vpi/sys_vcd.c
vpi/vcd_priv.h
vvp/README.txt

Writing parameters into VCD files makes the values available to waveform
tools. This can be done easily enough by writing out a $dumpadd section
at the beginning of the file that sets the parameter values. We don't need
to track the values over change, because by definition they do not change.
This changes the typical vcd output as well, so a few of the regression tests
need to be adjusted to account for this.
Also, while tracking this down, found and fixed the vvp/README.txt documention
for the .param/x records.
This fixes #156
TODO: Fix the fst dumper as well.

Add parameters to vcd dumps

---

ivtest/ivltests/assign_op_after_cmp1.v
ivtest/ivltests/assign_op_after_cmp2.v
ivtest/ivltests/real_array_store_after_cmp.v
ivtest/regress-sv.list
ivtest/regress-vlg.list
ivtest/regress-vlog95.list
tgt-vvp/stmt_assign.c

Most vvp load or store operations that take an index will check vvp flag 4.  If
the flag is not cleared load operations will return the out-of-bounds value and
store operations will be skipped. This is for handling the case where the index
is undefined.
There are a few places where flag 4 is not properly handled before a load or
store instruction, which can cause it to be skipped when it shouldn't be.
This happens in the following scenarios
* Assignment to immediate indexed real array entry
* Assignment operator on immediate indexed vector array entry
* Assignment operator on dynamic vector part select
E.g. the following will skip the assignment to `r[0]`.
```SystemVerilog
integer a = 0;
real r[1:0];
if (a == 0) 
r[0] = 1.23;
```
For the two immediate indexed assignments this resolved by …

tgt-vvp: Fix incorrect load or store operation skip

---

ivtest/gold/br_gh156.vcd.gold
ivtest/ivltests/br_gh156.v
vpi/sys_fst.c
vpi/sys_vcd.c

Parameters with real values are possible in Verilog, but not in the VCD
format, so lie a little and call them "real" objects. Otherwise, we can
treat them like constants and it works out, at least for gtkwave.
This fixes issue #717

Fix vcd dump of real value parameters

---

ivtest/ivltests/assign_op_oob.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
tgt-vvp/stmt_assign.c

If the index of an array access is known to be out-of-bounds during
elaboration it is replaced with 'x. In the tgt-vvp backend that is handling
compressed array assignments there is an assert() that triggers if the
index is an undefined immediate.
There is already an existing code path that is capable of handling
out-of-bounds access. Remove the assert and set the index to ULONG_MAX to
trigger taking the out-of-bound access path.
On this out-of-bounds path the write to the array is skipped. But this
leaves the result on the vector stack. Insert the `%pop/vec4` instruction
to make sure it is removed.
There is also an assert that gets triggered when the element value
of the array is wider than 32. Remove the assert and extend the
X value that gets pushed onto the stack to the right width …

 tgt-vvp: Fix out-of-bounds compressed assignment to arrays 

---

ivtest/ivltests/struct_packed_sysfunct2.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
tgt-vvp/draw_vpi.c

Access to members in packed struct fields is internally implemented using a
part select.
vvp has a special syntax for passing a part select of a vector to a system
function. This special syntax assumes that the part select is unsigned like
it is for normal Verilog part selects.
As a result passing a signed struct member to a system function will
interpret it as unsigned.
E.g.
```SystemVerilog
shortint x;
} s;
s.x = -1;
$display(s.x); // Will print 65535, should print -1
```
Add a check to make sure that the expression is actually unsigned. If it is
not fall back to evaluating the expression on the vector stack and pass the
value on the stack to the system function.

 tgt-vvp: Handle signedness when passing struct member to system function

---

ivtest/ivltests/assign_op_after_cmp3.v
ivtest/ivltests/assign_op_real_array.v
ivtest/ivltests/assign_op_real_array_oob.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
tgt-vvp/stmt_assign.c

The basic structure for supporting assignment operators on real arrays
exists in the tgt-vvp backend. But there are a few problems, most
importantly it generates the wrong instruction for loading data from the
real array.
The instruction it uses is `%load/reala`, but that instruction does not
exist, the correct name is `%load/ar`.
In addition to this there are a few minor problems.
* Out-of-bounds access on the array triggers an assert
* Missing `%pop/real` instruction when skipping a write due to
out-of-bounds access
Address these so assignment operators are supported on real array entries.

 tgt-vvp: Handle assignment operator on real array entries

---

vvp/compile.cc
vvp/opcodes.txt
vvp/vthread.cc

Remove some unused vvp instructions for the index words.
* `%mov/wu`: It is identical to `%ix/mov`
* `%cmp/ws` and `%cmp/wu`: These are for comparing index register and have not been used since the introduction of the vector stack

vvp: Remove unused index word instructions

---

ivtest/ivltests/nb_ec_array_pv.v
ivtest/ivltests/nb_ec_array_pv2.v
ivtest/ivltests/nb_ec_concat.v
ivtest/regress-ivl1.list
ivtest/regress-vlg.list
tgt-vvp/vvp_process.c
vvp/vthread.cc

A non-blocking event controlled assignment consists of 3 steps.
* Setup event
* Perform assignment
* Clear event
This works fine if the lvalue is a singular value. If the lvalue is a
concatenation multiple assignments are generated and the event is cleared
after each assignment. As a result only the first assignment is event
controlled. All other assignments will be regular non-blocking assignments.
E.g.
```SystemVerilog
reg x, y;
event e;
{x,y} <= @e 2'b11;
#1
$display(x, y); // x will be 1'b1, y will be 1'bx
```
To resolve this the event needs to be cleared after all assignments have
been done. This requires changes to both tgt-vvp and the vvp runtime.
tgt-vvp is updated to only insert a single `%evctl/c` instruction for each
event controlled non-blocking assignment.
The vvp runtime is …

Handle non-blocking event control to lvalue concatenation

---

ivtest/ivltests/nb_ec_multi_ev.v
ivtest/regress-vlg.list
tgt-vvp/vvp_process.c

When multiple events are used in a non-blocking event control they need to
be combined into a single event using `event/or`.
The generated `event/or` statement is missing the trailing semicolon and
newline, which results in parser error when vvp tries to run.
E.g.
```SystemVerilog
event e, f;
integer x;
x <= @(e or f) 10;
```
Add the missing semicolon and newline to fix this.

tgt-vvp: Fix syntax when using multiple events for non-blocking event control

---

ivtest/ivltests/pv_wr_vec2.v
ivtest/ivltests/pv_wr_vec2_nb.v
ivtest/ivltests/pv_wr_vec2_nb_ec.v
ivtest/ivltests/pv_wr_vec2a.v
ivtest/ivltests/pv_wr_vec2a_nb.v
ivtest/ivltests/pv_wr_vec2a_nb_ec.v
ivtest/ivltests/pv_wr_vec4.v
ivtest/ivltests/pv_wr_vec4_nb.v
ivtest/ivltests/pv_wr_vec4_nb_ec.v
ivtest/ivltests/pv_wr_vec4a.v
ivtest/ivltests/pv_wr_vec4a_nb.v
ivtest/ivltests/pv_wr_vec4a_nb_ec.v
ivtest/regress-sv.list
ivtest/regress-vlg.list
vvp/array.cc
vvp/vthread.cc

There are a few instructions that allow for partial writes to vectors. They all
have similar but not identical implementations.
When doing a partial write it is possible that the assigned value is either
partially or fully out-of-bounds. For partial out-of-bounds writes the value
needs to be truncated so that it is in bounds. For fully out-of-bounds writes
the assignment should be skipped.
There are two small problems with regards to the handling of out-of-bounds writes.
1) Non-blocking and non-blocking event controlled writes mix-up the target signal
width and value width, which can misclassify a fully out-of-bounds write on the
low side as a partial out-of-bounds write, which triggers an assert.
2) Blocking writes to arrays do not handle partial or fully out-of-bounds writes.
Trying to …

vvp: Improve partial vector write handling

---

Documentation/usage/command_line_flags.rst
driver/Makefile.in
driver/iverilog.man.in
driver/main.c

This allows for, e.g., a Makefile to find the location of vpi_user.h in a portable manner. Similar to pkgconfig.

Add -R option to print runtime paths (for now, includedir only)

---

vpi/vhdl_textio.c

Without this fix, ivlh_textio was failing at step 11 where the time is read from the file. This was because clang happens to put period directly after the units buffer on the stack. sscanf writes the terminating NUL overwriting the low byte of period, which is 100, so it returns 0.
These were the only two points where clang identified an issue.
Example clang warning fixed:
warning: 'sscanf' may overflow; destination buffer in argument 4 has size 2, but the corresponding specifier may require size 3 [-Wfortify-source]

Fix sscanf overflows

---

.github/workflows/test.yml

Github has [announced](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) that it is going to remove support for the Ubuntu 18.04 runner. It will start introducing temporary failures at increasing frequency in October 22 and completely remove support for it in April 23.
To avoid CI failing remove the Ubuntu 18.04 runner and add the 22.04 runner instead.

ci: Remove the Ubuntu 18.04 runner

---

PExpr.cc
PExpr.h
elab_expr.cc
ivtest/ivltests/sv_sign_cast1.v
ivtest/ivltests/sv_sign_cast2.v
ivtest/ivltests/sv_sign_cast3.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y
pform_dump.cc

SystemVerilog supports sign cast where it is possible to change the
signedness of an expression. Syntactical it is similar to width or type
casting, except that the keywords 'signed' or 'unsigned' are used in front
of the cast operator. E.g.
```SystemVerilog
logic [3:0] a = 4'b1000;
logic [7:0] b = signed'(a); // b is 8'b11111000;
logic signed [3:0] c = 4'b1000;
logic signed [7:0] d = unsigned'(c); // d is 8'b00001000;
```
As noted by the LRM section 6.24.1 ("Cast operator") applying a sign cast
to an expression is equivalent to calling the $signed() and $unsigned()
system functions on the expression.
This resolves #513.

Add support for SystemVerilog sign cast

---

ivtest/ivltests/module_inout_port_list_def.v
ivtest/ivltests/module_input_port_list_def.v
ivtest/ivltests/module_output_port_list_def.v
ivtest/regress-fsv.list
ivtest/regress-vlg.list
parse.y

Both Verilog (2005) and SystemVerilog support default port values for
variable output ports. SystemVerilog also supports default port values for
input ports. For port declaration lists it is possible to specify the
default value for port identifier.
E.g.
```systemverilog
module M (
input integer x, y = 1,
output integer z, w = 2
) ...
```
Currently the parser only supports specifying the default value for the
first identifier in the list. Extend the parser to also allow to specify
the default value for identifiers in the list.
This resolves #754.

Support default port values in port declarations lists

---

README.md

Fixes #729. I reformatted the README to comply with Github Markdown syntax.

Convert README.txt to Markdown

---

elab_type.cc
ivtest/ivltests/struct_packed_darray_fail.v
ivtest/ivltests/struct_packed_queue_fail.v
ivtest/ivltests/struct_packed_uarray_fail.v
ivtest/ivltests/union_packed_darray_fail.v
ivtest/ivltests/union_packed_queue_fail.v
ivtest/ivltests/union_packed_uarray_fail.v
ivtest/regress-sv.list

Unpacked dimensions for struct or union members are currently silently
discarded. E.g.
```SystemVerilog
struct packed { int x[2]; } s;
```
will elaborate successfully as a struct with a non-array int typed field.
This should instead elaborate to an unpacked array of ints typed field. And
subsequently, since unpacked arrays are not allowed in a packed struct or
union, result in an error instead.

Handle unpacked dimensions for struct and union members

---

.github/workflows/test.yml

Github had [deprecated MacOS 10.15 runner](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/) and it has now been removed and the corresponding test always fails. Similar to the Windows runner use the `latest` version to auto-upgrade the environment to a supported version.

ci: Upgrade macOS runner

---

t-dll.cc
tgt-vlog95/scope.c

For modules with parameters the vlog95 backend generates one module
declaration for each module instance. This is done so that different values
for the module parameters can be supported.
Local parameters are guaranteed to have the same value for all module
instances though. Add support for detecting the case that all module
parameters are local parameters and in that case only create one shared
module declaration. This is similar to what the vhdl backend does.

tgt-vlog95: Consider scopes with only localparams as unique

---

PWire.cc
PWire.h
elab_sig.cc
ivtest/ivltests/module_port_typedef_array1.v
ivtest/ivltests/sv_typedef_nested_array.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y
pform.cc
pform.h

If the type of a port is an array type it currently always gets evaluated
in the scope where the port is declared.
But if the type is a typedef it might be declared in a different scope and
must be evaluated in that scope. E.g. the following will declare an array
port with 10 entries and an element type of a 5 bit vector, while it should
declare one with 4 entries and an element type of a 2 bit vector.
```SystemVerilog
localparam A = 2;
localparam B = 4;
typedef [A-1:0] T[B];
module test (
T x
);
localparam A = 5;
localparam B = 10;
endmodule
```
This is in part due to array types being given special handling. This was
necessary before because each base type required slightly different
handling and so the base type had to be extracted from the array type.
This has now been consolidated …

Correctly handle unpacked array typedefs for ports

---

elab_expr.cc
ivtest/ivltests/sv_class_return.v
ivtest/regress-sv.list

There is nothing special to do for return class objects from a function.
They can be handled the same as other objects such as dynamic arrays and
queues.
But there currently is an assert in the code that handles function calls
assigned to objects that will trigger if the target type is not an queue or
dynamic array.
This is because Icarus allows dynamic arrays to be initialized with a
single value and for that the element with of the dynamic array needs to be
known, so the single value expression can be evaluated correctly.
Since classes can not be initialized from vector expressions the width does
not matter in that case.
Update the code to only query the element width if the target type is an
dynamic array or queue and pass a placeholder value of 1 for the width
otherwise.

Support class objects as function return values 

---

ivtest/ivltests/sv_darray_copy_empty1.v
ivtest/ivltests/sv_darray_copy_empty2.v
ivtest/ivltests/sv_darray_copy_empty3.v
ivtest/ivltests/sv_darray_copy_empty4.v
ivtest/ivltests/sv_queue_copy_empty1.v
ivtest/ivltests/sv_queue_copy_empty2.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
vvp/vthread.cc

An empty dynamic array or queue is represented by a null object in vvp.
Currently when trying to copy such an object results in undefined behavior
in various places. Either hitting an assert or causing a nullptr
dereference.
Make sure that the empty object is handled correctly by treating it as a
special case.

vvp: Handle copying of empty dynamic array and queue

---

ivtest/ivltests/sv_ps_function1.v
ivtest/ivltests/sv_ps_function2.v
ivtest/ivltests/sv_ps_function3.v
ivtest/regress-sv.list
parse.y

The parser currently only allows package scoped functions to be called if
there is at least one argument. But package scoped functions are the same
as normal functions and it is allowed to call them with no arguments. It is
even possible to pass no value for a positional argument, if the positional
argument has a default value.
Update the parser to handle this.
Also fix a small memory leak when parsing function calls where the
argument list is not freed.

Allow package scoped functions to be called without arguments 

---

ivtest/ivltests/sv_ps_function4.v
ivtest/ivltests/sv_ps_type1.v
ivtest/ivltests/sv_ps_var1.v
ivtest/regress-sv.list
parse.y

In order to avoid conflicts in the grammar the lexer distinguishes between
identifiers and type identifiers. To correctly classify an identifier the
lexer needs to know in which scope a token is parsed. E.g. when the parser
encounters a package scope operator it calls `lex_in_package_scope()` to tell
the lexer which scope the following identifier should be classified in.
Currently the `lex_in_package_scope()` is only used when a type identifiers is
parsed, but on for normal identifiers. As a result it is not possible to
reference variables or function from a package scope that have the same
name as a type identifier in the current scope. E.g.
```SystemVerilog
package P;
int T;
endpackage
module test;
typedef int T;
initial $display(P::T);
endmodule
```
Another problem is that in …

Improve parsing of package scoped identifiers 

---

elab_expr.cc
ivtest/ivltests/sv_class_method_default1.v
ivtest/ivltests/sv_class_method_default2.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

For class function method calls currently only as many arguments as have
been supplied are elaborated. Any trailing arguments that might have default
values are skipped. This will trigger an assertion later on in the vvp code
generator backend.
Fix this by making sure that all arguments of the function are evaluated.
Note that this already works correctly for class task method calls.
This resolves #441

Handle default argument values for class function method calls 

---

PExpr.cc
ivtest/ivltests/automatic_error14.v
ivtest/ivltests/automatic_error15.v
ivtest/regress-sv.list

The `PEIdent::has_aa_term()` method still uses the old `symbol_search()`
and will fail to find the variable if part of the identifier path is a
member select of a variable.
As a result such writes to fields of automatic structs can be classified as
static and it is possible to do non-blocking assignments to them. E.g.
```SystemVerilog
task automatic t;
logic x;
} s;
s <= ...; // This fails
s.x <= ...; // This works, but should fail
endtask
```
Switch to the new symbol search to make sure this case is handled
correctly. The new symbol search will correctly handle identifier paths
that have a trailing item after the variable, while the old symbol search
will always return an error in that case.
Note that while it is not allowed to do a non-blocking write to a class
object …

Prevent non-blocking writes to fields of automatic structs

---

lexor.lex
lexor_keyword.gperf
parse.y
parse_misc.cc
pform.cc
pform_analog.cc
pform_disciplines.cc
pform_package.cc
pform_pclass.cc

While building on NetBSD I found that a bunch of files either use "va_list" or they #include a header that uses "va_list" without #including the required <cstdarg> header. 
I'm going to guess that Linux has some header file that #includes stdarg when NetBSD doesn't. 
I added <cstdarg> to most include lists that needed it. There was one case where <cstdarg> was already there, but not early enough in the list and so I moved it to the front of the list of included header files.

Add #include <cstdarg> to all source files that use va_list

---

elaborate.cc
ivtest/ivltests/sv_class_method_call_void.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

Calling a void function (or a regular function and ignoring the result)
from within a class method will currently result in an error unless the
void function itself is a method of the same class.
This is because we add the implicit `this` as an object on which to search
for the function and if we do not find it print an error. Change this to
only print an error if the implicit this was not added and it was a method
call on an object identifier.
This resolves #410 and #419.

Handle calling void function from class method

---

PWire.cc
PWire.h
configure.ac
elab_scope.cc
elab_sig.cc
elab_type.cc
ivtest/ivltests/module_port_typedef_vector.v
ivtest/ivltests/sv_ps_type_cast1.v
ivtest/ivltests/sv_ps_type_cast2.v
ivtest/ivltests/sv_ps_type_class1.v
ivtest/ivltests/sv_ps_type_enum1.v
ivtest/ivltests/sv_ps_type_expr1.v
ivtest/ivltests/sv_ps_type_expr2.v
ivtest/ivltests/sv_ps_type_struct1.v
ivtest/ivltests/sv_typedef_chained.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_func_eval.cc
parse.y
pform_dump.cc
pform_pclass.cc
pform_types.h

Currently when referencing a typedef this gets replaced with the
`data_type_t` that the typedef points to. This works for most cases, but
there are some corner cases where it breaks down.
E.g. it is possible to have a scoped type identifier which references a
type defined in a package. For such type identifiers, only the data_type_t
itself is remembered, but not the package scope. This will cause the type
identifier to be elaborated in the wrong scope.
Furthermore type identifiers of vector types used for module or task port
might not be elaborated in the correct scope.
Introduce a new `typeref_t` which has `data_type_t` as a base type and can
be used as the data type for a signal. A new instance of a `typeref_t` is
created when referencing a type identifier. The `typeref_t` remembers …

Improve handling of type identifier references 

---

elab_expr.cc
ivtest/ivltests/struct10.v
ivtest/regress-sv.list

This patch corrects range indexing of members in structs such as:
bit [0:7] [7:0] a;
bit [0:15] b;
} bar;

Support for range indexing of arrays with swapped ranges within structs

---

elaborate.cc
ivtest/ivltests/br_gh793.v
ivtest/regress-vlg.list

Trying to add a drive strength or delay to a undriven net will result in an
assertion. Make sure that a driver is added to undriven nets.
A driver is already added for all NetESignals, which covers most expression that
can produce a raw net rvalue. But there are other ways we can end up with just a
net as the rvalue, e.g.  when applying a sign cast to a net. The following
example triggers the issue
```SystemVerilog
wire [7:0] a;
wire [7:0] b = $signed(a);
```
This addresses #793

 Insert drivers for undriven nets

---

vvp/vpi_callback.cc
vvp/vpi_vthr_vector.cc

I noticed the master branch would not compile under redhat7.9, an obsolete release but still common in the digital CAD industry. The attached small patch fixes the problem by explicitly referencing the standard C++ library. This is should be harmless on other systems but I haven't got a suitable system to try at the moment, except OSX which is OK with it.

Explicitly refer to std::isnan to avoid clash with system standard library

---

ivtest/ivltests/genvar_compressed.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y
pform.cc
pform.h

SystemVerilog supports using compressed assignment operators for the genvar
for loop variable update.
Add support for this in a similar way as increment/decrement operators by
transforming the statement to its uncompressed equivalent. E.g. `x += y`
gets transformed to `x = x + y`.

 Support compressed assignment statements for genvar loops

---

PScope.cc
PScope.h
elab_scope.cc
elab_type.cc
ivtest/ivltests/sv_typedef_circular1.v
ivtest/ivltests/sv_typedef_circular2.v
ivtest/ivltests/sv_typedef_fwd_base.v
ivtest/ivltests/sv_typedef_fwd_class.v
ivtest/ivltests/sv_typedef_fwd_enum1.v
ivtest/ivltests/sv_typedef_fwd_enum2.v
ivtest/ivltests/sv_typedef_fwd_enum3.v
ivtest/ivltests/sv_typedef_fwd_enum_fail.v
ivtest/ivltests/sv_typedef_fwd_struct.v
ivtest/ivltests/sv_typedef_fwd_struct_fail.v
ivtest/ivltests/sv_typedef_fwd_union.v
ivtest/ivltests/sv_typedef_fwd_union_fail.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
lexor.lex
net_scope.cc
netlist.h
parse.y
parse_misc.h
pform.cc
pform.h
pform_dump.cc
pform_package.cc
pform_types.cc
pform_types.h

SystemVerilog supports forward type declarations. This allows to declare a
type identifier and use it, e.g. in a signal declaration, before declaring
what the actual type is. The type still needs to be fully defined
eventually in the same scope as its forward type declaration. E.g.
```SystemVerilog
typedef T;
T x;
typedef int T;
```
The forward type definition can also contain the kind of the type it is
going to be. E.g struct, union, class, etc. The LRM calls this the basic
type. If the actual type is not of the basic type specified in the forward
type declaration this is an error. E.g.
```SystemVerilog
typedef struct T;
typedef int T; // Error, int is not a struct
```
It is legal to have more than one forward type declaration for the same
type name, as long as the basic type is the …

Add support for forward type declarations

---

elaborate.cc

Rather than moving one item at a time form the elaboration_work_list to the temporary queue use std::swap to exchange them all at once. This is a bit more efficient.

Use std::swap() to exchange elaboration_work_list

---

design_dump.cc
elaborate.cc
ivtest/ivltests/br_gh801.v
ivtest/regress-sv.list
net_proc.cc
parse.y
pform_dump.cc
synth2.cc

It is legal systemverilog to have empty init statements in the for-loop statement. This unrolls as a while loop, and presumes that the programmer has handled loop variable initialization elsewhere. This precludes some clevernesses like synthesis or loop unrolling, but that should not be a problem in general.
This resolves #801

Handle empty for-loop init statement

---

PScope.h
elab_scope.cc
elab_type.cc
ivl.def
ivl_target.h
ivtest/ivltests/sv_type_param1.v
ivtest/ivltests/sv_type_param2.v
ivtest/ivltests/sv_type_param3.v
ivtest/ivltests/sv_type_param4.v
ivtest/ivltests/sv_type_param5.v
ivtest/ivltests/sv_type_param6.v
ivtest/ivltests/sv_type_param7.v
ivtest/ivltests/sv_type_param_fail1.v
ivtest/ivltests/sv_type_param_fail2.v
ivtest/regress-sv.list
net_design.cc
net_scope.cc
netlist.h
parse.y
pform.cc
pform.h
pform_types.h
t-dll-api.cc
t-dll.cc
t-dll.h
tgt-vhdl/scope.cc
tgt-vhdl/state.cc
tgt-vlog95/scope.c
tgt-vvp/vvp_scope.c

SystemVerilog supports type parameters. These are similar to value
parameters, but they allow to pass a type to a module or similar when
instantiating it.
E.g.
```SystemVerilog
module A #(parameter type T = int);
endmodule
module B;
A #(.T(real)) i_a;
endmodule
```
Add support for handling type parameters.
For the vlog95 and vhdl backends type parameters, similar to typedefs, get
replaced with their actual value. For modules with non-local type
parameters for each module instance a unique module or architecture is
generated with the actual type.
Querying type parameters through VPI is not yet supported.
This resolves #417

 Support type parameters

---

elab_scope.cc
elab_sig.cc
ivtest/ivltests/sv_ps_type_class_prop.v
ivtest/ivltests/sv_typedef_fwd_class2.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

Elaboration uses a multi stage approach. Currently non-static class
properties are elaborated during the scope elaboration phase. This can
cause problems if the type of a property is declared in a different scope.
In that case it is possible that the scope in which the type is defined has
not been elaborated yet and the type is not available. E.g.
```SystemVerilog
package P;
typedef int T;
endpackage
class C;
P::T x;
endclass
```
Another area where this is problematic is when a class has a property of a
another class that has a forward declaration. In this case the type of the
forward declared class, which is created when the scope is elaborated, is
not available when the scope of the class that is using it is elaborated.
E.g.
```SystemVerilog
typedef class B;
class A;
B b;
endclass
class …
```

 Elaborate class properties during signal phase instead of scope phase

---

design_dump.cc
elaborate.cc
ivtest/ivltests/br_gh801b.v
ivtest/regress-sv.list
net_proc.cc
parse.y
pform_dump.cc
synth2.cc

The for_step statement is optional in for loops. For example this:
```
for (idx = 0 ; idx < 5 ; ) begin
idx += 1;
end
```
is valid.  Not necessarily synthesizable, but valid Verilog.

Allow for for_step of for loops to be optional

---

PExpr.cc
PWire.cc
PWire.h
elab_sig.cc
parse.y
pform.cc
pform_dump.cc

With the refactoring of the type support complete and the parser being mostly type agnostic there are 2 small cleanups that can be done in the parser support code.
- Remove `ivl_variable_type_t` from `PWire`. Each `PWire` now either has an explicit data_type_t attached from which the base type can be queried or it is a implicit typed variable in which case it is a 4-state vector.
- `pform_make_task_ports_vec` and `do_make_task_ports` look very similar now and can be consolidated

Post type support refactoring cleanup

---

PExpr.cc
PExpr.h
ivtest/ivltests/automatic_error16.v
ivtest/ivltests/automatic_error17.v
ivtest/ivltests/automatic_error18.v
ivtest/regress-sv.list

If the base expression of a cast expression has an automatic term then the
cast expression itself has an automatic term.
Make sure this is implemented so that an error is properly reported when
using such an expression in a context where automatic variables are not
allowed.

 Implement has_aa_term() for cast expressions

---

ivtest/ivltests/sv_array_query.v
ivtest/regress-sv.list
netmisc.cc

Unpacked array dimensions that are specified with only a single size value
(C-style unpacked arrays) have a $left of 0 and a $right of $size - 1. E.g.
`x[10]` is equivalent to `x[0:9]`. This is defined in the LRM (1800-2017)
section 7.4.2 ("Unpacked arrays").
Currently it is implemented the other way around. There are a few contexts
where this distinction matters. For example array to array assignments,
which supposed to be done left-to-right and not high-to-low.

Fix $left/$right for C-style unpacked arrays

---

elab_expr.cc
elab_scope.cc
ivtest/ivltests/sv_class_virt_new_fail.v
ivtest/regress-sv.list
netclass.h
parse.y
pform.h
pform_pclass.cc
pform_types.h

It is not allowed to create objects of virtual classes. Currently the
virtual keyword is accepted by the parser, but otherwise ignored.
Keep track of whether a class is virtual and generate an error when the
class new operator is used for a virtual type.
Resolves #421.

Do not allow to create objects of virtual classes

---

elab_expr.cc
ivtest/ivltests/func_void_in_expr_fail.v
ivtest/ivltests/task_in_expr_fail.v
ivtest/regress-sv.list
ivtest/regress-vlg.list

Tasks and void functions can not be called as part of an expression. Currently both result in an internal assert. Make sure that an error is reported instead.

Report errors for task and void function calls in expressions

---

elab_expr.cc
elab_type.cc
pform.cc
t-dll.cc
tgt-vhdl/state.cc
vhdlpp/parse.y
vhdlpp/parse_types.h
vvp/vpi_callback.cc
vvp/vpi_cobject.cc
vvp/vpi_const.cc
vvp/vpi_priv.cc
vvp/vpi_time.cc
vvp/vpi_vthr_vector.cc

Clean up warnings that show up on newer compilers. Many of these warnings are related to obsolete c library features or language features. This does not clear up warnings in code generated by bison or flex.

Clean up warnings

---

Statement.h
elaborate.cc
ivtest/ivltests/sv_void_cast1.v
ivtest/ivltests/sv_void_cast2.v
ivtest/ivltests/sv_void_cast3.v
ivtest/ivltests/sv_void_cast4.v
ivtest/ivltests/sv_void_cast_fail1.v
ivtest/ivltests/sv_void_cast_fail2.v
ivtest/ivltests/sv_void_cast_fail3.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y

SystemVerilog has explicit support for calling a function
as a statement. This is allowed when the function call is encapsulated in
`void'(...)`. E.g. `void'(f(1, 2, 3));`
We already support calling function calls as statements without the void
cast and emit a warning when doing so.
Adding support for void casts only requires to update the parser to handle
the void cast and then do not emit the warning if a function is called as
a statement as part of a void cast.
Void casting a task or void function call is not allowed and will generate
an elaboration error.
Also be consistent between allowing to call non-void function and non-void
class methods as statements. The former currently generates a warning
the latter an error. Change it so that both report a warning.
Resolves #434

 Add support for void cast function call

---

ivtest/ivltests/sv_class_compat1.v
ivtest/ivltests/sv_class_compat2.v
ivtest/ivltests/sv_class_compat_fail1.v
ivtest/ivltests/sv_class_compat_fail2.v
ivtest/ivltests/sv_class_compat_fail3.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
netclass.cc
netclass.h

SystemVerilog allows objects to be assigned to a variable that is a base
type of the objects type.
E.g.
```SystemVerilog
class B; endclass
Class C extends B; endclass
C c = new
B b = c;
```
Add a type_compatibility() method for netclass_t that allows these kinds of
assignments.
This already works fine in vvp since, as SystemVerilog does not support
multiple inheritance, properties will always be at the same offset in the
base class and the inheriting class.

 Allow objects to be assigned to a variable of a base class 

---

elab_scope.cc
ivtest/ivltests/sv_class_method_lt_static1.v
ivtest/ivltests/sv_class_method_lt_static2.v
ivtest/ivltests/sv_class_method_var_init.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y
pform.cc
pform.h
pform_pclass.cc

Up to 1800-2017 the grammar in the LRM allowed an optional lifetime
qualifier for class declarations. Icarus supports this and uses this as the
default lifetime for methods of the class. But the LRM never specified what
this qualifier should do actually actually. [Starting with 1800-2023 the
qualifier will be removed from the grammar](https://accellera.mantishub.io/view.php?id=3561).
Furthermore the LRM states that methods of a class are supposed to have
automatic storage and static storage is forbidden.
This currently works in Icarus for the most part since the liftime attached
to class methods is ignored during elaboration in most places. Where it
does not work is for variable initializers where it results in broken code
being generated and vvp crashes at runtime. E.g.
```SystemVerilog …
```

 Fix variable initialization in class methods

---

PExpr.cc
PExpr.h
elab_expr.cc
ivtest/ivltests/sv_class_new_typed1.v
ivtest/ivltests/sv_class_new_typed2.v
ivtest/ivltests/sv_class_new_typed3.v
ivtest/ivltests/sv_class_new_typed_fail1.v
ivtest/ivltests/sv_class_new_typed_fail2.v
ivtest/ivltests/sv_class_new_typed_fail3.v
ivtest/ivltests/sv_class_new_typed_fail4.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y

By default when creating a new class object the type of the object is
determined by the type of the target.
SystemVerilog also allows to explicitly specify the type of the object to
be created. The specified class still needs to be assignment compatible
with the target. This is e.g. useful to construct an object of a derived
class of the target. E.g.
```SystemVerilog
class B; ... endclass
class C extends B; ... endclass
B b;
b = C::new;
```
Add support for this to the parser as well as handling it during
elaboration.

 Add support for typed constructor calls

---

PExpr.h
elab_expr.cc
elab_lval.cc
elaborate.cc
ivtest/ivltests/sv_class_super3.v
ivtest/ivltests/sv_class_super4.v
ivtest/ivltests/sv_class_super5.v
ivtest/ivltests/sv_class_super6.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_assign.cc
net_expr.cc
netlist.h
netmisc.h
parse.y
pform_dump.cc
symbol_search.cc
t-dll-proc.cc

SystemVerilog allows to use the `super` keyword to access properties and
methods of a base class. This is useful if there is for example an
identifier with the same name in the current class as in the base class and
the code wants to access the base class identifier.
To support this a bit of refactoring is required. Currently properties are
internally referenced by name, this does not work if there are multiple
properties of the same. Instead reference properties always by index.
In addition when looking up an identifier that resolves to an object return
both the type and the object itself. This is necessary since both `this`
and `super` resolve to the same object, but each with a different type.
Also support `this.super` which behaves the same as `super`.
Resolves #671

Add support for handling `super` keyword 

---

.github/workflows/test.yml
ivtest/regress-v13.list

msys2 [removed the gperf package from the base-devel](https://github.com/msys2/MSYS2-packages/commit/085698dce3b5e481f0db586173d0157c8e5c8ff9) package collection.
Add gperf explicitly to the dependency list, without this the Windows
CI will fail.
Also fix the following warning `=> WARNING: MINGW_INSTALLS is deprecated, use MINGW_ARCH instead`

 ci: Windows: Add gperf to dependency list

---

elab_expr.cc
ivtest/ivltests/size_cast_fail1.v
ivtest/ivltests/size_cast_fail2.v
ivtest/ivltests/size_cast_fail3.v
ivtest/regress-sv.list

Size casts are only allowed if the value is positive. For cases where it is
0 negative or undefined an error should be reported. Currently the negative
case is not handled. Extend the test to also check for negative values.

 Report an error for size casts with a negative value

---

ivtest/ivltests/always_comb_void_func.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_nex_input.cc

Internally void function calls are modeled as task calls. But unlike task
calls, access to a signal inside a void function is supposed to contribute
to the sensitivity list of an always_comb block.
Make sure that the same logic applied for non-void functions is also
applied for void functions.
Resolves #539

Let void functions in always_comb block contribute to sensitivity list

---

ivlpp/lexor.lex
ivtest/ivltests/macro_comment1.v
ivtest/ivltests/macro_comment2.v
ivtest/ivltests/macro_comment3.v
ivtest/ivltests/macro_comment_multiline.v
ivtest/regress-vlg.list

A '*' or '/' directly following a C-style comment in a macro currently
triggers the detection of the start of another comment. Fix this by first
looking for a '/' that should start the comment.
Also add support for handling multi-line comments in macros.

ivlpp: Improve handling of comments in macros

---

elab_type.cc
ivtest/ivltests/struct_packed_member_def.v
ivtest/regress-sv.list

SystemVerilog allows struct members to have default values specified as
part of the struct declaration. But this is only allowed for unpacked
structs. For packed structs an error should be reported. This is defined in
section 7.2.2 ("Assigning to structures") of the LRM (1800-2017).
Currently default member values are just silently discarded if specified
for a packed struct. Make sure to report an error instead.

Report error for packed struct default member values

---

ivtest/regress-sv.list

The parameter_no_default test is expected to pass in SystemVerilog mode. Make sure the expected result is correctly annotated in the results file.

regress-sv: Fix expected result for parameter_no_default test

---

elab_expr.cc
ivtest/ivltests/sv_ps_function5.v
ivtest/ivltests/sv_ps_function6.v
ivtest/ivltests/sv_ps_function7.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
tgt-vlog95/scope.c

`PECallFunction::test_width()` does not consider the package scope and will
not return any information for package scoped function calls.
As a result in contexts where the width or sign of a expression must be
known produces the wrong result when using a package scoped function.
Make sure to search for the function name in the package scope if a package
is specified.
Also update the vlog95 backend to handle signed return types so the new
regression tests work with vlog95 backend.

Fix width and sign determination for package scoped function calls

---

elab_expr.cc
elab_lval.cc
ivtest/ivltests/sv_ps_member_sel1.v
ivtest/ivltests/sv_ps_member_sel2.v
ivtest/ivltests/sv_ps_member_sel3.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

There are a few cases where a member select on a package scoped identifier
is evaluated in the scope of the package rather than the scope where the 
identifier is referenced.
This leads to incorrect behavior if a local symbol is used as an index in a
part select of the referenced member select. E.g.
```SystemVerilog
package P;
localparam N = 1;
logic [3:0] x;
} s = 4'b0101;
endpackage
module test;
localparam N = 2;
initial $display(P::s.x[N]); // Will print 0, should print 1
endmodule
```
Use the scope where the member select is used, rather than the scope where
the identifier is defined, to fix this.

Elaborate member selects in the scope where they are used

---

PExpr.h
elab_expr.cc
ivtest/ivltests/sv_ps_function_fail1.v
ivtest/ivltests/sv_ps_function_fail2.v
ivtest/ivltests/sv_ps_function_fail3.v
ivtest/regress-sv.list

Currently a package scoped function call will result in an assert if the
function does not exist in the package scope.
For non-package scoped function calls instead a proper error is reported.
Refactor the code to share the same code paths between package scoped and
non-package scoped function calls. This makes sure that errors are reported
in both cases. It also makes the code slightly smaller.

Improve error handling for package scoped function calls

---

PExpr.h
elab_lval.cc
ivtest/ivltests/sv_class_static_prop4.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
netclass.cc

Classes are allowed to access properties of the base class. This also
includes static properties. Currently when looking up a static property
only those of the class itself are considered. Extend this to also consider
properties of the base classes.

Allow access to static properties of base classes

---

elab_net.cc
ivtest/ivltests/sv_ps_array_cassign.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

Make sure the package scope is considered when elaborating identifiers for
continuous unpacked array assignments.

Handle continuous array assignments from package scoped indentifiers

---

ivtest/ivltests/sv_string8.v
ivtest/ivltests/sv_string9.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
vvp/vthread.cc

The `%pushi/str` and `%concati/str` instructions should remove null-bytes
from the string literal when converting it to a SV string. This is defined in
section 6.16 ("String data type") of the LRM (1800-2017).
This is already handled correctly when converting a vector from the stack
to a SV string, just not when converting a string literal to SV string.

 vvp: Remove null-bytes when converting string literals to SV strings

---

ivtest/gold/br_gh827.gold
ivtest/gold/macro_with_args.gold
ivtest/ivltests/br_gh827.v
ivtest/ivltests/string13.v
ivtest/ivltests/string14.v
ivtest/regress-vlg.list
tgt-vlog95/misc.c
tgt-vlog95/numbers.c
vvp/vpi_const.cc
vvp/vpi_priv.cc

There are currently three different ways how null-bytes are handled when reading a value as vpiStringVal through the VPI API.
1) For string literals the null-byte is treated as the end of the string all further bytes are ignored
2) For literals all null-bytes are ignored
3) For signals any leading null-bytes are ignored, non-leading null-bytes are replaced with a space
The first one is clearly a bug and needs to be fixed. 2) and 3) could both be considered valid implementations since the LRM is not very clear on what should happen to null-bytes for vpiStringVal.
But for consistency we should use the same implementation for all 3 variants. This change implements variant 3), which means removing only leading null-bytes and replace others with spaces. This this based on the consensus that …

vvp: Handle null-bytes in a conistent way when reading through VPI

---

.github/workflows/test.yml

The github CI VM has multiple CPUs. 2 for Linux and Windows, 3 for macOS. Make use of parallel build to speed up the CI tests a bit.
For Windows the `makepkg-mingw` command already schedules a parallel build, so no changes are made to the Windows build.
This speeds up the build part of the Linux and MacOS steps, which allows them to finish earlier. Unfortunately the bottleneck for the CI execution time is running the regression test suite on the Windows VM, which is almost 10x slower than on the Linux VM.

ci: Use parallel build

---

PExpr.cc
PExpr.h
elab_expr.cc
ivtest/ivltests/sv_ps_method1.v
ivtest/ivltests/sv_ps_method2.v
ivtest/ivltests/sv_ps_method3.v
ivtest/ivltests/sv_ps_method4.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
parse.y

Currently package scoped function calls are supported. Update the parser
and elaboration to also allow method calls on packaged scoped variables.

Support method calls on package scoped signals

---

ivtest/ivltests/sv_import_hier_fail1.v
ivtest/ivltests/sv_import_hier_fail2.v
ivtest/ivltests/sv_import_hier_fail3.v
ivtest/regress-sv.list
symbol_search.cc

Imported identifiers should only be visible in the scope they have been
imported too. They should not be accessible through hierarchical names into
that scope. This is defined in section 26.3 ("Referencing data in
packages") of the LRM (1800-2017).
Modify the symbol search to not look at imports if the name is part of a
hierarchical path.

Don't allow access to imported identifiers through hierarchical names

---

Statement.h
design_dump.cc
elaborate.cc
emit.cc
ivl.def
ivl_target.h
ivtest/ivltests/br_gh191_break.v
ivtest/ivltests/br_gh191_continue.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_func_eval.cc
net_proc.cc
netlist.h
parse.y
pform_dump.cc
t-dll-api.cc
t-dll-proc.cc
t-dll.h
target.cc
target.h
tgt-stub/statement.c
tgt-vlog95/scope.c
tgt-vlog95/stmt.c
tgt-vvp/Makefile.in
tgt-vvp/vvp_priv.h
tgt-vvp/vvp_proc_loops.c
tgt-vvp/vvp_process.c

Implement the "continue" and "break" loop control statements. These are two of the three "jump statements" described in the IEEE1800-2017, section "12.8 Jump statements". These statements control the flow within the loop statements (for, forever, foreach, while, and do-while) and are only meaningful within those loops. For an obviously contrived example:
```verilog
idx = 0;
forever begin
idx += 1;
if (idx < 2)
continue;
break;
end
```
At the pform (annotated parse tree) and netlist (elaborated design tree) phases, these statements present as normal statements, with no special trickery needed. This PR adds the parser support and elaborate support to handle them. They are also pretty straightforward in the ivl_target API and the stub target, so the support is there as well. The ivl_target …

Add break and continue loop control statements support

---

PExpr.h
elab_expr.cc
elab_lval.cc
elaborate.cc
ivtest/ivltests/sv_class_prop_shadow1.v
ivtest/ivltests/sv_class_prop_shadow2.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
netmisc.h
symbol_search.cc

There are currently two mechanisms for handling class properties. One that
is used when a class property is accessed through an object and other when
a class property is used freestanding in a class method.
Both are very similar, but there are some small differences. E.g. one
supports arrays, the other supports nested properties.
```SystemVerilog
class B;
int x;
endclass
class C;
B b;
B ba[2];
task t;
ba[0] = new; // Does work
this.ba[0] = new; // Does not work
b.x = 10; // Does not work
this.b.x = 10; // Does work
endtask
```
There is another problem where free standing properties take precedence
over local variables. E.g.
```SystemVerilog
class C;
int x = 1;
task t();
int x = 2;
$display(x); // Should print 2, will print 1
endtask
endclass
```
The class property elaboration also ignores …

Consolidate class property handling

---

PExpr.cc
elab_expr.cc
elaborate.cc
ivtest/ivltests/func_empty_arg1.v
ivtest/ivltests/func_empty_arg2.v
ivtest/ivltests/func_empty_arg3.v
ivtest/ivltests/func_empty_arg_fail1.v
ivtest/ivltests/func_empty_arg_fail2.v
ivtest/ivltests/func_empty_arg_fail3.v
ivtest/ivltests/func_empty_arg_fail4.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list
net_func.cc
parse.y

SystemVerilog allows to call a function with empty arguments if the function specifies a default value. Address a few small issues around this.
1) If the same function is invoked multiple time and using default port values, each invocation ends up with the same NetExpr. This results in undefined behavior as there are now multiple owners of that NetExpr. To avoid this duplicate the default port value each time it is used.
2) There are two places that do not account for empty function arguments, resulting in a NULL pointer deref. This happens for detecting implicit nets in function call arguments and detection automatic terms in function call arguments.
3) Trailing empty arguments are pruned from function and task calls. This means no error is reported when too many empty arguments are …

Improvements for calling functions with empty arguments

---

PExpr.cc
PExpr.h
Statement.cc
Statement.h
elab_expr.cc
elab_lval.cc
elab_net.cc
elab_sig.cc
elaborate.cc
ivtest/ivltests/sv_ps_hier_fail1.v
ivtest/ivltests/sv_ps_hier_fail2.v
ivtest/regress-sv.list
netmisc.h
pform_dump.cc
pform_types.h
symbol_search.cc

In SystemVerilog identifiers can usually have an additional package scope
in which they should be resolved. At the moment there are many places in
the code base that handle the resolution of the package scope.
Add a common data type for package scoped paths as well as a
`symbol_search()` variant that works on package scoped identifiers. This
allows to handle package scope resolution in a central place.
Having the code in a central place makes it easier to ensure consistent and
correct behavior. E.g. currently it is possible to access identifiers through a
scoped name, that are visible in the scope, but not declared in the scope
itself. E.g.
```SystemVerilog
int x;
package P;
int y;
endpackage
module test;
initial begin
$display(P::x); // Should fail
$display(P::y); // OK
end
endmodule
``` …

Add common implementation for scoped symbol search

---

ivtest/ivltests/br_gh800.v
ivtest/regress-sv.list

Issue #800 is apparently not a problem with the compiler, but with the regression test suite. This PR adds a detailed test that shows the correct output, but on windows, the compare with the gold file seems to not work. The issue is wrapped around the \r\n characters being treaded weird on Windows machines. So do address this, change the test to not use the gold file, and instead self-test by looking at values that are assigned to the string.
fixes #800

Add br_gh800 test

---

PPackage.h
PScope.h
ivtest/ivltests/sv_export1.v
ivtest/ivltests/sv_export2.v
ivtest/ivltests/sv_export3.v
ivtest/ivltests/sv_export4.v
ivtest/ivltests/sv_export5.v
ivtest/ivltests/sv_export6.v
ivtest/ivltests/sv_export_fail1.v
ivtest/ivltests/sv_export_fail2.v
ivtest/ivltests/sv_export_fail3.v
ivtest/ivltests/sv_export_fail4.v
ivtest/ivltests/sv_export_fail5.v
ivtest/ivltests/sv_export_fail6.v
ivtest/regress-sv.list
parse.y
pform.cc
pform.h
pform_package.cc

By default an identifier that has been imported into a package is not
available for imports by other packages. Only imports that have been
exported can be imported again. E.g.
```SystemVerilog
package P1;
int x;
endpackage
package P2;
import P1::x;
export P1::x;
endpackage
module test;
import P2::x; // This will only work if x has been exported.
endmodule
```
Exports follow the same syntax as imports and allow both export of specific
identifiers or wildcard export. Export supports the special `*::*` target,
which will export all imported items.
Add support for handling package exports.
There is one special cases that needs to be considered. Usually when using
wildcard imports from multiple packages it is an error if there multiple
import candidates for an identifier. With exports it is …

Add support for package export

---

PExpr.h
elab_expr.cc
ivtest/ivltests/sv_ap_parray1.v
ivtest/ivltests/sv_ap_parray2.v
ivtest/ivltests/sv_ap_parray_fail1.v
ivtest/ivltests/sv_ap_parray_fail2.v
ivtest/ivltests/sv_ap_parray_fail3.v
ivtest/ivltests/sv_ap_struct1.v
ivtest/ivltests/sv_ap_struct2.v
ivtest/ivltests/sv_ap_struct_fail1.v
ivtest/ivltests/sv_ap_struct_fail2.v
ivtest/regress-sv.list
net_design.cc
netmisc.cc
netstruct.h

SystemVerilog allows to use assignment patterns to assign a value to a
packed array or packed struct typed variable.
This is similar to using a concatenation, with the difference that for
concatenations the values are evaluated in a self-determined context and
for assignment patterns they are evaluated in a context defined by the
element type of the packed array or the member type of the struct.
This means that the value is for example automatically width expanded or
truncated if it does not have the same size as the element type. Automatic
type conversion is also done when allowed. E.g.
```SystemVerilog
bit [3:0][3:0] x = '{1'b1, 32'h2, 3.0, "TEST"};
$display("%x", x); // -> 1234
```
Nested assignment patterns are also supported. E.g.
```SystemVerilog
byte x;
bit …
```

Add initial support for packed array and packed struct assignment patterns

---

config.sub

This generates a fresh copy of config.sub.
The existing config.sub calls 64-bit ARM targets `aarch64`, which is the official name for the target. However, Apple targets go by the name `arm64-apple`. As a result, this platform was not recognized.
This gets iverilog building on Apple targets with 64-bit ARM processors.

regenerate config.sub

---

ivtest/run_ivl.py

vvp_reg.py requires 4 gold files. One for each of stdout and stderr of both iverilog and vvp. Most of these log files will be empty for most test cases. This will result in a lot of empty files being added to the repository.
If a gold file for a specific output stream can not be found assume that the output stream is supposed to empty. This allows to omit the empty gold files.
Also remove all the existing empty gold files.

vvp_reg.py: Allow to omit empty gold files

---

elab_net.cc
ivtest/ivltests/sv_ap_parray3.v
ivtest/ivltests/sv_ap_parray4.v
ivtest/ivltests/sv_ap_struct3.v
ivtest/ivltests/sv_ap_struct4.v
ivtest/regress-sv.list
ivtest/regress-vlog95.list

Currently when creating the NetNet for a continuous assignment to an array
element the type of the element is flattened into a canonical 1 dimensional
form. This works for most cases because packed types are compatible if
their total packed with is the same.
But there are some contexts such as if the right-hand-side is an assignment
pattern where the actual type matters and flattening the type will result
in incorrect behavior.
Retain the original type of the array element when creating the NetNet for
the array element assignment.

Handle continuous assignment of assignment patterns to array elements

---

ivtest/gold/sdf_header-vvp-stdout.gold
ivtest/ivltests/sdf_header.sdf
ivtest/ivltests/sdf_header.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sdf_header.json
vpi/sdf_parse.y

This PR adds some printfs to output all the information about the SDF header.
I think this behavior is useful because this output is only printed on `-sdf-info` or `-sdf-verbose` and if you specify these arguments, you probably want all the information.
This PR adds the following output:
- SDF Version
- Divider
- Voltage (triple or scalar)
- Temperature (triple or scalar)
Which values are chosen from the min:typ:max expressions is determined with the `-Tmin|typ|max` argument passed to iverilog.
I tried to match the indentation style as it is, but it wasn't always clear to me what to choose. I think a unified indentation style, enforced by an auto formatter, would benefit Icarus very much. (But that's something for another time.)
I created a test (`sdf_header`) that reads in an sdf file …

Print more information about the SDF header

---

netlist.h

The port_index_ member of the NetNet is not initialized which can lead to undefined behavior. Make sure to initialize to -1 to indicate that the net is not associated with any port.
Resolves #890

Initialize NetNet::port_index_

---

elaborate.cc
ivtest/ivltests/task_return1.v
ivtest/ivltests/task_return2.v
ivtest/ivltests/task_return_fail1.v
ivtest/ivltests/task_return_fail2.v
ivtest/regress-vvp.list
ivtest/vvp_tests/task_return1.json
ivtest/vvp_tests/task_return2.json
ivtest/vvp_tests/task_return_fail1.json
ivtest/vvp_tests/task_return_fail2.json
netlist.h

SystemVerilog allows to use the `return` statement in a task to exit the
task before it reaches the end of its execution. This is defined in section
13.3 ("Tasks") of the LRM (1800-2017).
This is similar to using `disable` to stop a task from within itself with
the difference that `disable` will affect all concurrently running
executions of a task, while `return` will only affect the task from which
it has been called.
The `%disable/flow` vvp instruction allows to implement the required
behavior for task return.
There is one complication in that it is not allowed to call return from
inside a parallel block (fork-join). If a parallel block is unnamed and has
no variable declarations there won't be a NetScope for it. So it is not
possible to detect whether the return is inside a parallel …

Support return in tasks

---

ivtest/ivltests/final3.v
ivtest/regress-vvp.list
ivtest/vvp_tests/final3.json
vvp/schedule.cc
vvp/vthread.cc
vvp/vthread.h

In the current implementation a `%fork` instruction in a final block will
get scheduled, but never executed.
And while SystemVerilog requires a `final` procedure to execute in 0 time
and so no SystemVerilog `fork` is allowed inside of it, there are some
other scenarios where iverilog generates `%fork` statements.
For example when declaring variables in a sub-block a sub-scope with its
own thread is is used to allocate the storage for those variables and
`%fork` is used to execute the child thread.
E.g. the following, while being valid SystemVerilog, will never execute the
loop because the generated code will implement the loop as a child thread
being executed by a `%fork` statement.
```SystemVerilog
final for (int i = 0; i < 10; i++) $display(i);
```
To mitigate this treat final …

vvp: Handle `%fork` in `final` procedures

---

elaborate.cc
ivtest/ivltests/module_port_array1.v
ivtest/regress-vvp.list
ivtest/vvp_tests/module_port_array1.json

The current check to decide whether a port is an array or a scalar signal
uses the number of pins on the NetNet. If it is larger than one the code
assumes that it is an array.
But for arrays with on a single element the number of pins will be 1 and
the port is incorrectly treated as a scalar signal which results in an
error.
Instead of using the number of pins check for the number of unpacked
dimensions to decide whether the port is an array.
Resolves #915

Fix connecting single element array ports

---

vvp/vpi_callback.cc

Directly casting a negative double to a unsigned integer type is undefined behavior and has different results on x86 and ARM based platforms.
On x86 the behavior is similar to casting a signed int to an unsigned integer, i.e. the sign bit will end up in the MSB. But on ARM the result will be 0.
To get consistent behavior, first cast to signed integer and then cast the signed integer value to an unsigned integer value.
Resolves #917

Fix formatting real to binary and hex strings on ARM

---

ivtest/gold/sdf_header-vvp-stdout.gold
vpi/sdf_parse.y

This PR moves `SDF INFO`, `SDF WARNING`, `SDF ERROR` to the beginning of the line to make it consistent with existing behavior and for better readability.
The corresponding gold file has been updated, and three empty gold files have been removed that I had mistakenly kept.

Move `SDF INFO`,  `SDF WARNING`, `SDF ERROR` to start of line

---

ivtest/ivltests/pv_wr_fn_vec2.v
ivtest/ivltests/pv_wr_fn_vec4.v
ivtest/regress-vvp.list
ivtest/vvp_tests/pv_wr_fn_vec2.json
ivtest/vvp_tests/pv_wr_fn_vec4.json
vvp/vthread.cc

Partial out-of-bounds write to a function's return value will trigger an
assert, even though the operation is valid.
The assert checks that the truncated value has the expected width, but
instead it should check that the non-truncated value has the expected with.
Move the assert before the truncation to fix this.
This resolves #927

Fix incorrect assert for partial oob write to function return value

---

ivtest/gold/sv_immediate_assert.gold
ivtest/gold/sv_immediate_assume.gold
ivtest/ivltests/sv_immediate_assert.v
ivtest/ivltests/sv_immediate_assume.v
parse.y

Updated parse.y to add labels. Also added labelled assert/assume in existing tests. Updated GOLD files accordingly. Fixes #897

Added support for labels in immediate assert/assume

---

ivtest/ivltests/br_gh191_break.v
ivtest/ivltests/br_gh191_continue.v
tgt-vvp/vvp_priv.h
tgt-vvp/vvp_proc_loops.c
tgt-vvp/vvp_process.c

Currently continue and break are supported in most loops. But not in
do-while loops. Add support for them in do-while loops as well.

Handle continue/break in do-while loops

---

ivtest/ivltests/constfunc16.v
ivtest/ivltests/constfunc17.v
ivtest/ivltests/constfunc18.v
ivtest/ivltests/constfunc19.v
ivtest/ivltests/constfunc20.v
ivtest/regress-vvp.list
ivtest/vvp_tests/constfunc16.json
ivtest/vvp_tests/constfunc17.json
ivtest/vvp_tests/constfunc18.json
ivtest/vvp_tests/constfunc19.json
ivtest/vvp_tests/constfunc20.json
net_func_eval.cc
netlist.h

Add support for `continue` and `break` in constant functions. This is done
in a similar way to how `disable` is implemented for constant functions.
Two new global flags are introduced `loop_break` and `loop_continue` that
get set when evaluating the corresponding statement. If either of these
flags are set all other statements are ignored until the end of a loop is
reached. At the end of the loop both `loop_break` and `loop_continue` get
cleared. If `loop_break` was set before clearing it the loop is exited.

Support continue/break in constant functions

---

ivtest/ivltests/sv_wildcard_import8.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_wildcard_import8.json
main.cc
parse_api.h
pform.cc

SystemVerilog requires that functions and tasks are not implicitly imported
if a symbol with the same name appears in the scope, even if it the symbol
is declared after its usage.
To support this a list of potential imports is collected while parsing a
scope and only when the end of the scope is reached it is evaluated whether
the symbol should be imported or not based on whether it already exists in
the scope.
This currently works fine for all scopes except for the unit scope. Since
the unit scope might span multiple files it is never explicitly closed and
the potential imports are never checked.
Make sure that after parsing all files is done the potential imports for
the unit scope are checked.
Resolves #928

Handle implicit task/function imports in the unit scope 

---

ivtest/gold/br_gh939-iverilog-stderr.gold
ivtest/ivltests/br_gh939.v
ivtest/regress-vlg.list
ivtest/regress-vvp.list
ivtest/run_ivl.py
ivtest/vvp_tests/br_gh939.json
parse.y

Two small fixes/changes for implicit named port connections.
- Use the correct line location
- Require SystemVerilog mode
-  Regression test `br_gh315` is modified to run in SystemVerilog mode since it
makes use of implicit named port connections.
In order to regression test for the line information also add support for gold files for CE type tests  to vvp_reg.py.
Resolves #939

Fix line location and require SystemVerilog mode for implicit named port connections

---

elaborate.cc
ivtest/ivltests/module_ordered_list1.v
ivtest/ivltests/module_ordered_list2.v
ivtest/regress-vvp.list
ivtest/vvp_tests/module_ordered_list1.json
ivtest/vvp_tests/module_ordered_list2.json

The current implementation expects that for a module instantiation with a
ordered list connection all ports are supplied.
But there doesn't seem to be such a requirement in the LRMs. The Verilog
LRM doesn't mention anything in this regard and the SystemVerilog LRM
mentions in section 23.3.2.1 that a blank or omitted port connection is
either left unconnected or uses the default value of the port.
Update the implementation so that it allows to omit trailing ports and only
generates an error message if too many ports are specified in the ordered
port list.
Resolves #931

 Allow to omit trailing module ports in ordered list connection

---

ivtest/gold/br_ml20190814.gold
vpi/sdf_parse.y

This PR adds a warning, to indicate that timing checks are currently not supported.
Additionally there is a cleanup to how some warnings and errors are printed.

SDF: Add TIMINGCHECK warning

---

vpi/sys_sdf.c

Currently, using the wildcard character `*` for cell instance specification in an SDF file results in a segfault due to null pointer access.
With this PR, only a warning will be printed instead:
```
SDF WARNING: top.v:30: Wildcard cell instance specification (*) currently not supported.
```
Also some cleanup regarding warning/error printing.

SDF: Implement warning for wildcard cell instanciation

---

Module.cc
PExpr.cc
PFunction.cc
PGate.cc
PTask.cc
PWire.cc
Statement.cc
elab_expr.cc
elab_lval.cc
elab_net.cc
elab_scope.cc
elab_sig.cc
elaborate.cc
expr_synth.cc
net_assign.cc
net_event.cc
net_expr.cc
net_func_eval.cc
net_scope.cc
netlist.cc
netmisc.cc
pform.cc
pform_disciplines.cc
pform_package.cc
pform_pclass.cc
symbol_search.cc

`ivl_assert()` is similar to `assert()` except that it will also include source file and line information about the expression for which the assert was triggered.
Use `ivl_assert()` instead of `assert()` where the line information is available. This will generate better bug reports and make it easier to diagnose why an assert is triggered.

Replace assert() with ivl_assert() where line information is available

---

eval_tree.cc
net_expr.cc
netlist.cc
netlist.h
tgt-vvp/stmt_assign.c

The are many binary operations where if the two operands are 2-state the result is guaranteed to be 2-state.
This is true for all arithmetic operation with the exception of division where division by 0 will always result in 'x even if the inputs are both 2-state.
The same is true for all binary bitwise operators as well as the binary logical operators.
Having the expression type be 2-state avoids some unnecessary %cast2 instructions that would otherwise get inserted when assigning the result to a 2-state variable.
E.g without this change the following will result in
```
int a, b, c;
b = a + b;
```
will result in
```
%load/vec4 ...;
%load/vec4 ...;
%add;
%cast2;
%store/vec4 ...;
```
For binary comparison operators this is already handled.

Make result of binary operations 2-state if inputs are 2-state

---

ivtest/ivltests/module_output_port_list_def.v
ivtest/ivltests/module_port_array_init1.v
ivtest/regress-vvp.list
ivtest/vvp_tests/module_port_array_init1.json
parse.y

At the moment there are two rules for port declarations. One that allows
the port to be declared as an unpacked array, the other that allows to
specify an initializer expression.
SystemVerilog allows both to be specified in the same port declaration. Add
support for this to the parser.

Support initializer expression for unpacked array port declarations 

---

elab_expr.cc
ivtest/ivltests/bitsel11.v
ivtest/regress-vvp.list
ivtest/vvp_tests/bitsel11.json

Bit selects on packed arrays are always unsigned and have a width of 1.
Element selects on a multi-dimensional packed array are always unsigned and
have the width of the element.
At the moment a element or bit select on the last level element of a
multi-dimensional signed array will incorrectly yield a signed expression.
Commit 40b36337e2c8 ("Fix some bugs with packed array dimensions") added
some special checks to fix the width on multi-dimensional array element
selects. But this removed the unsigned attribute from bit selects.
Commit 81947edaa5e9 ("A bit select is not the same as selecting part of a
packed array") fixed this for single dimensional packed array, but left it
broken for multi-dimensional arrays.
Commit 7c024d6cab16 ("Fix width calculation for bit/part selects of …

Fix bit select on signed multi-dimensional packed array

---

ivtest/ivltests/sv_module_port1.v
ivtest/ivltests/sv_module_port2.v
ivtest/ivltests/sv_module_port3.v
ivtest/ivltests/sv_module_port4.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_module_port1.json
ivtest/vvp_tests/sv_module_port2.json
ivtest/vvp_tests/sv_module_port3.json
ivtest/vvp_tests/sv_module_port4.json
parse.y

In Verilog it is possible to declare multiple ports as part of the same
port declaration. Ports declared this way all have same direction, signal
kind and data type. E.g.
```SystemVerilog
module M (input [3:0] a, b, c); ...
```
SystemVerilog extends this and allows to override on a per port basis
certain port attributes. E.g. redefine just the data type
```SystemVerilog
module test (input [3:0] a, [1:0] b, int c); ...
```
Or to just redefine the port kind
```SystemVerilog
module test(input [3:0] a, var b, wire c); ...
```
It is even possible to leave out the direction for the very first port. As
long as at least one other property of the port is specified. In that case
the direction will default to `inout`. E.g.
```SystemVerilog
module test(integer a, b, c); ...
```
Furthermore it is …

 Support SystemVerilog style partial ANSI port declarations

---

net_expr.cc

arith_expr_type() queries the expression type of its two child nodes up to two times. Since the child nodes might also need to query their child nodes expression type to determine their own this can lead to an exponential runtime.
For complex expressions this can easily result in very long elaboration time.
Avoid this by querying the expression type only once for each child node.
Resolves #967

Avoid exponential execution time behavior in arith_expr_type()

---

Makefile.in
Module.h
PTimingCheck.cc
PTimingCheck.h
elaborate.cc
ivtest/ivltests/timing_check_delayed_signals.v
ivtest/ivltests/timing_check_syntax.v
ivtest/regress-vvp.list
ivtest/vvp_tests/timing_check_delayed_signals.json
ivtest/vvp_tests/timing_check_syntax.json
parse.y
pform.cc
pform.h
pform_dump.cc

Since timing checks are currently not supported in Icarus Verilog, they are ignored. This is an issue for some models:
Both `$setuphold` and `$recrem` have support for negative timing checks. For this to work, delayed versions of the reference and data signals must be created. The model has access to these delayed signals. The current situation is that these signals are never assigned.
This PR does what is proposed under 15.5.4 Option behavior in the standard. When timing checks are disabled (or in the case of Icarus Verilog not yet supported) the delayed reference and data signals become copies of the original reference and data signals.
For example, with the following timing check:
$setuphold(posedge sig1, negedge sig2 , 0:0:0 , 0:0:0 , notifier , cond1 , cond2 , del_sig1 , del_sig2 ) ; …

Handle delayed signals in timing checks as assignments

---

ivtest/ivltests/sv_automatic_2state.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_automatic_2state.json
vvp/vvp_net.cc
vvp/vvp_net.h
vvp/vvp_net_sig.cc
vvp/vvp_net_sig.h
vvp/words.cc

Automatic 2-state vectors currently get initialized to 'hx, while their
default value should be 0.
Make sure the vector is initialized to 0 at the beginning of the automatic
context.

 vvp: Initialize automatic 2-state vectors to 0

---

ivtest/ivltests/sv_const_fail9.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_const_fail9.json
parse.y

Commit 3daa2982acb2 ("Add support for `const` variables") added support for
constant variables, but had a small mistake and did propagate the constant
flag from the parser if the variable is declared with the `var` keyword.
Still allowing to modify those variables. Fix this.

Make sure `const var` variables are constant

---

elab_expr.cc
elaborate.cc
ivtest/ivltests/sv_chained_constructor1.v
ivtest/ivltests/sv_chained_constructor2.v
ivtest/ivltests/sv_chained_constructor3.v
ivtest/ivltests/sv_chained_constructor4.v
ivtest/ivltests/sv_chained_constructor5.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_chained_constructor1.json
ivtest/vvp_tests/sv_chained_constructor2.json
ivtest/vvp_tests/sv_chained_constructor3.json
ivtest/vvp_tests/sv_chained_constructor4.json
ivtest/vvp_tests/sv_chained_constructor5.json
netclass.cc
netclass.h
pform_pclass.cc

There are some corner cases around class constructor chaining that can
result in chained constructors not being called, or being called multiple
times.
This is primarily related to that a class can have either an explicit
constructor called `new` and an implicit constructor called `new@` and how
the lookup of them is done.
Lookup is currently done independently for the implicit and explicit
constructor using the `method_from_name()` method. `method_from_name()`
will search the whole class hierarchy for a class method. If a class
doesn't have a method by that name it will look in the parent class and so
on.
As a result the lookup for the explicit constructor can return the explicit
constructor of a parent class if the class itself only has an implicit
constructor and vice versa.
E.g. in …

 Fix class constructor chaining corner cases

---

vvp/vvp_net.cc

Fixes #985
This PR ensures that whenever any `vvp_net_t`s are connected via `vvp_net_t::link`, nodes with `vvp_fun_modpath_src` are always inserted at the head of the linked list.
This guarantees that `vvp_fun_modpath_src`  are always evaluated before their respective `vvp_fun_modpath`, without any runtime penalty.

Always evaluate `vvp_fun_modpath_src` first

---

Documentation/developer/guide/vvp/vvp.rst
ivtest/ivltests/sv_argumentless_func.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_argumentless_func.json
tgt-vvp/vvp_scope.c
vvp/parse.y

Fixes #979
Although, it doesn't pass the test case I added. It looks like using continuous assignment from functions doesn't work for argumentless functions.
The output from the test I added is the following:
```plain
FAILED -- test_assign=zz, expect 01
```

Argumentless functions fix

---

ivlpp/lexor.lex
ivtest/ivltests/attrib_expr.v

This was noticed while using Vivado which does the expansion in pragma comments.
I am not sure the test is the right place to add it. Let me know if I need to update this.

add double quote escapes from pragma comments.

---

PExpr.h
PWire.h
Statement.h
design_dump.cc
elab_expr.cc
elab_lval.cc
elab_sig.cc
elab_type.cc
elaborate.cc
eval_tree.cc
expr_synth.cc
netenum.cc
netenum.h
netlist.cc
netlist.h
netmisc.cc
netmisc.h
netparray.cc
netparray.h
netstruct.cc
netstruct.h
nettypes.cc
nettypes.h
netvector.cc
netvector.h
synth2.cc
t-dll-api.cc
t-dll.cc
t-dll.h

A set of small cleanups around netrange_t, no functional changes.
- Use `NetNet` constructor that does not take a `vector<netrange_t>` for non-array nets
- Use `netrange_width()` in a few more places
- Add typedef `netranges_t` for `vector<netrange_t>`
- Replace the one place where `list<netrange_t>` is used with `netranges_t`
- Remove unused `calculate_count()` function

Small cleanups around netrange_t

---

ivtest/ivltests/sv_2state_array_init_prop.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_2state_array_init_prop.json
vvp/array.cc

For 2-state non-automatic arrays currently real 0.0 value is propagated as
the initial value. This will cause an assert at the downstream receivers
which expect a vector.
Make sure that the vector value 0 is propagated instead for 2-state
vectors.

 vvp: Fix initial value propagation for 2-state non-automatic arrays

---

ivtest/ivltests/sv_queue_vec.v
ivtest/regress-fsv.list
ivtest/regress-sv.list
tgt-vvp/eval_vec4.c

vvp does not track whether the values stored in a dynamic array or queue are 2-state or 4-state. Internally the data is always stored as 4-state.
To make sure that the read value is actually 2-state do a cast for 2-state reads.
E.g. performing an out-of-bounds access on a 2-state dynamic array or queue will yield `'X` while it should return `'0`.
There is one test that relies on the incorrect behavior. Update the test to use a 4-state instead of 2-state base type.

Return '0 for out-of-bounds access on 2-state queues and dynamic arrays.

---

ivtest/ivltests/sv_array_cassign8.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_array_cassign8.json
vvp/parse.y

vvp is missing a parser rule for unsigned 2-state net arrays. E.g.
```SystemVerilog
bit a[0:1];
assign a[0] = 1'b0;
```
will synthesize fine, but when running it with vvp cause a syntax error.
Resolves #1005

vvp: Add parser rule for unsigned 2-state net arrays

---

.github/workflows/test.yml

The MINGW32 test is failing randomly. It is not something that we typically need anyhow, so give up and remove it.
Fixes #1050 .

Remove MINGW32 from regression test scripts

---

ivtest/run_ivl.py

Commit 56c5bf1da1d4 ("ivtest: Remove regress v11, v12, and v13") removed the `expected_fail` argument from the `check_run_outputs()` function, but did not remove all references. This causes the run_ivl.py script to fail. The script is part of the CI pipeline and causes all PRs to fail.
Remove the remaining references to `expected_fail` to make it work again.

Fix run_ivl.py

---

elab_expr.cc
ivtest/ivltests/partsel_invalid_idx1.v
ivtest/ivltests/partsel_invalid_idx2.v
ivtest/ivltests/partsel_invalid_idx3.v
ivtest/ivltests/partsel_invalid_idx4.v
ivtest/ivltests/partsel_invalid_idx5.v
ivtest/ivltests/partsel_invalid_idx6.v
ivtest/regress-vvp.list
ivtest/vvp_tests/partsel_invalid_idx1.json
ivtest/vvp_tests/partsel_invalid_idx2.json
ivtest/vvp_tests/partsel_invalid_idx3.json
ivtest/vvp_tests/partsel_invalid_idx4.json
ivtest/vvp_tests/partsel_invalid_idx5.json
ivtest/vvp_tests/partsel_invalid_idx6.json

The elaboration of the base expression of a vector slice index can fail and return a nullptr. Currently this results in a nullptr deref. Handle that case by exiting the function early.
Resolves #1036.

Handle invalid vector slice base expressions

---

vvp/array.cc

An initial value propagation should only be scheduled for variable array ports, but not for net array port since those do not contain any values.
This got accidentally broken when fixing support for 2-state variable array ports.
Add a check that only does the initial value propagation if the port is for a variable array.
Test case in #1014.

vvp: Don't schedule initial value propagation for net array ports

---

ivtest/ivltests/array_slice_concat.v
ivtest/regress-vlg.list
ivtest/regress-vvp.list
ivtest/vvp_tests/array_slice_concat.json

ivtest: add array_slice_concat

---

elab_expr.cc
elab_lval.cc
elab_net.cc
ivtest/ivltests/partsel_reversed_idx1.v
ivtest/ivltests/partsel_reversed_idx2.v
ivtest/ivltests/partsel_reversed_idx3.v
ivtest/ivltests/partsel_reversed_idx4.v
ivtest/ivltests/partsel_reversed_idx5.v
ivtest/ivltests/partsel_reversed_idx6.v
ivtest/regress-vvp.list
ivtest/vvp_tests/partsel_reversed_idx1.json
ivtest/vvp_tests/partsel_reversed_idx2.json
ivtest/vvp_tests/partsel_reversed_idx3.json
ivtest/vvp_tests/partsel_reversed_idx4.json
ivtest/vvp_tests/partsel_reversed_idx5.json
ivtest/vvp_tests/partsel_reversed_idx6.json

The order of the indices of a part select need to match the order in which
the dimension of a packed array has been declared. E.g. if the msb is less
than the lsb in the declaration it also has to be for the part select.
If the order of the part select is the opposite of the declaration this is
an error. This works as expected for part selects on the most outer
dimensions.
But for inner dimensions the current implementation just swaps the msb and
lsb of the part select if they are in the wrong order.
Refactor this so that an error is reported for both the outer and inner
dimensions.

 Detect reversed part select on inner dimensions

---

PExpr.h
elab_expr.cc
ivtest/ivltests/struct_nested1.v
ivtest/regress-vvp.list
ivtest/vvp_tests/struct_nested1.json

The current `PEIdent::test_width()` method is only able to calculate width
of a path with up to two elements.
For more complex paths it will not be able to calculate the width. E.g.
* Nested struct member access
* function call of a enum member in a struct
To make nested structures work properly walk the whole path tail element
by element updating the type along the way. Also take the indices into
account and update the type if an arrays dimensions have been fully
consumed.
Resolves #704.

Correctly calculate width of nested path identifiers

---

expr_synth.cc
vvp/concat.cc
vvp/vvp_net.h

Currently replication in a concatenation is implemented by simply
concatenating the input signals multiple times by the replication amount.
Replace this to use NetReplicate on the concatenation instead. In case
there is only one input vector to the concatenation the replication will directly
connect to the input vector.
This is slightly more efficient in vvp since the replication functor has
only one input while the concatenation has multiple inputs connected to the
same wire. When an update of the input occurs the replication functor will
only receive a single update, while the concatenation will receive multiple
update events, one for each replication.

 Use NetReplicate to implement replication for concat

---

vvp/vvp_net.h

vvp_net_ptr_t uses vvp_sub_pointer_t to implement a tagged pointer with the tag containing the port number.
The size of the tagged pointer is that of a normal pointer and could easily be passed in a register when passing it as an argument to a function.
But since the vvp_sub_pointer_t type has a non-standard destructor it is instead passed on the stack with the register containing a pointer to the stack location where the value is stored.
This creates extra boiler plate code when passing a vvp_net_ptr_t to a function writing and reading the value to and from the stack.
Use the default destructor for vvp_sub_pointer_t to avoid this and have the value passed in a register.
There isn't much of a performance gain but the change is simple enough to do anyway.

vvp: Reduce overhead of passing vvp_net_ptr_t between functions

---

vvp/part.cc

The part functor has no real typed state and the bitsr field of the state struct is unused. Remove it.

vvp: Remove bitsr from struct vvp_fun_part_state_s

---

ivtest/gold/pr1963962-fsv.gold
ivtest/regress-fsv.list

Starting with commit 96df251c955a ("Suppress unnecessary VCD/LXT/LXT2 warnings about packages.") there is no longer a warning printed that the unit scope can't be printed if it is empty.
Remove the special SystemVerilog mode gold file for the pr1963962 test that expects this warning.

ivtest: Remove outdated pr1963962 SystemVerilog mode gold file

---

ivtest/run_ivl.py

To escape the `.` in the regex it needs to be prefixed with a `\`. But since the `\` is a escape character in python strings it needs to be escaped as well.
Without this some versions of python print the following warning:
run_ivl.py:36: SyntaxWarning: invalid escape sequence '\.'
match= re.search(b'Icarus Verilog version ([0-9]+)\.([0-9]+)', text)

run_ivl.py: Properly escape `.` in regex

---

ivtest/ivltests/br_gh497a.v
ivtest/ivltests/part_sel_port.v
ivtest/ivltests/pr1002.v
vvp/concat.cc
vvp/concat.h
vvp/vpi_priv.cc
vvp/vvp_net.h

A concat typically has multiple inputs. Whenever one of the input values
change the output value of the concat is updated and propagated to its
downstream consumers.
When multiple inputs change within the same cycle each input will cause a
update propagation. Depending of the overall structure of the design this
can cause a significant performance penalty.
E.g. the following synthetic structure has a exponential runtime increase
based on the value of N.
```SystemVerilog
reg [N-1:0] x;
generate for (genvar i = 0; i < N - 1; i++)
assign x[i+1] = ^{x[i],x[i]};
endgenerate
```
To improve this defer the value propagation of the concat to the end of the
current cycle, this allows multiple input updates to be included in a
single output update.
For the example in report #1052 this reduced the …

vvp: Improve concat performance

---

ivtest/ivltests/single_element_array.v
ivtest/regress-vvp.list
ivtest/vvp_tests/single_element_array.json
tgt-vvp/vvp_scope.c

Also, add a test. This fixes #1113.

Update handling of single-element arrays.

---

.github/workflows/test.yml
.gitignore

This fixes problems found when building a Mac version of libvvp.so for testing.  A successful build can be seen attached to the source branch.
The change of runner is peculiar: it seems that  github has started using ARM runners for "macos-latest" and the Homebrew build of bison seems broken.  Evidence [here](https://github.com/gatk555/iverilog/actions/runs/9495787460/job/26168769019) until I purge the old logs.  Look at top and bottom of the "Build, check and install" section.
Description:
Fix test.yml for Mac by fixing docopt and using Macos-12 runner.
Update the versions of called Actions to prevent warnings and add "workflow_dispatch" to allow testing.
Unrelated: add "*.so" to .gitignore to hide built libvvp.so.

Revive Action test.yml.

---

tgt-vvp/eval_vec4.c
tgt-vvp/stmt_assign.c
tgt-vvp/vvp_proc_loops.c

For sequences where the tgt-vvp backend generates `%pushi` followed by one of the operations that have an immediate version replace it with the immediate version. This is slightly more efficient.

tgt-vvp: Replace `%pushi ...; %op` with `%opi`

---

ivtest/ivltests/vardly_undefined_vec.v
ivtest/regress-vvp.list
ivtest/vvp_tests/vardly_undefined_vec.json
tgt-vvp/vvp_process.c

Assignments with an undefined delay should be treated like assignments with
zero delay. For the most part this is implemented correctly, except for
assignments to a part of a vector where the offset inside the vector is an
immediate value. E.g.
```SystemVerilog
reg [1:0] x;
integer d = 'x;
...
x[0] <= #d 1'b1
```
Here when loading the delay into the index register flag 4 is updated, but
never cleared afterwards. As a result, if the delay is undefined, the vector
assignment will be skipped. Fix this by making sure flag 4 is always
cleared before the vector assignment instruction.

Fix vector assignment with undefined delay

---

ivtest/ivltests/shift6.v
ivtest/regress-vvp.list
ivtest/vvp_tests/shift6.json
tgt-vvp/eval_expr.c

When loading a signal into into an index register currently the signedness of the signal is used when deciding whether sign-extension should be performed or not. But this can lead to incorrect results, instead the signedness of the expression must be used as that might be different from the signal. E.g.
```SystemVerilog
reg signed [1:0] = 2'b10;
$display(1 << x[1:0]);
```
gives the wrong result without this.
Resolves #1165

tgt-vvp: Use signedness of expression instead of signal for index load

---

ivtest/ivltests/br_gh1155.v
ivtest/regress-vvp.list
ivtest/vvp_tests/br_gh1155.json
tgt-vvp/vvp_scope.c

When multiple words in one array were connected to the same nexus as a  single word array, the code generator was sometimes failing to generate all the necessary aliases. This was highly dependent on the elaboration order.
This fix should be more robust, but there are currently no tests in the  test suite that cause the compiler to generate whole-array aliases, and I can't think of a way to make it do so as we don't yet support unpacked arrays in module ports, so that branch of the code is currently untested.

Fix vvp cg array word aliasing

---

elab_expr.cc
elab_lval.cc
elab_net.cc
ivtest/ivltests/partsel_outside_const.v
ivtest/ivltests/partsel_outside_expr.v
ivtest/regress-vvp.list
ivtest/vvp_tests/partsel_outside_const.json
ivtest/vvp_tests/partsel_outside_expr.json
netmisc.cc
vvp/part.cc

Internally, the maximum address space of a vector is 31 bits + a sign bit
to signal invalid addresses (out of bounds or has one or more x or z bits).
This pull request ensures that unsigned parts-select bit addresses which would
otherwise overflow and wrap around within this address space are correctly
handled as out of bounds.

Guard against overflow / wrap around of internal bit address

---

aclocal.m4

Newer version of the linker on MacOS provide a deprecation warning when using the `-undefined` flag with the `suppress` value. This is cause CI to fail to do logs not matching when building VPI modules.
Switch to using the `dynamic_lookup` value for the flag instead, which resolves the warning and is the behavior we want when loading the module.

Use `-undefined dynamic_lookup` for linking loadable modules on MacOS

---

tgt-vvp/eval_real.c
tgt-vvp/eval_vec4.c
tgt-vvp/stmt_assign.c
tgt-vvp/vvp_process.c

Remove implicit casts between vector and real in tgt-vvp. These are not required since any implicit cast in the source will be converted to an explicit cast in the elaboration stage.

tgt-vvp: Remove implicit casts between vector and real

---

ivtest/ivltests/sv_class_prop_logic.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_class_prop_logic.json
vvp/class_type.cc

Logic type class properties use the wrong constructor resulting in a default value of a vector with 0 width. Switch to the right constructor to fix this.

vvp: Fix logic class property initialization

---

ivtest/ivltests/sv_class_prop_assign_op1.v
ivtest/ivltests/sv_class_prop_assign_op2.v
ivtest/ivltests/sv_darray_assign_op.v
ivtest/ivltests/sv_queue_assign_op.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_class_prop_assign_op1.json
ivtest/vvp_tests/sv_class_prop_assign_op2.json
ivtest/vvp_tests/sv_darray_assign_op.json
ivtest/vvp_tests/sv_queue_assign_op.json
tgt-vvp/stmt_assign.c

Add support for assignment operators on class properties and dynamic array or queue elements. With a little bit of refactoring most of the code can be shared with the existing assignment operator support for scalars and arrays.

Add support for assignment ops on class properties and dynamic array or queue elements

---

ivtest/ivltests/sv_class_prop_nest_darray1.v
ivtest/ivltests/sv_class_prop_nest_obj1.v
ivtest/ivltests/sv_class_prop_nest_real1.v
ivtest/ivltests/sv_class_prop_nest_str1.v
ivtest/ivltests/sv_class_prop_nest_vec1.v
ivtest/regress-vvp.list
ivtest/vvp_tests/sv_class_prop_nest_darray1.json
ivtest/vvp_tests/sv_class_prop_nest_obj1.json
ivtest/vvp_tests/sv_class_prop_nest_real1.json
ivtest/vvp_tests/sv_class_prop_nest_str1.json
ivtest/vvp_tests/sv_class_prop_nest_vec1.json
tgt-vvp/stmt_assign.c

Currently nested lvalues are only supported for vector typed properties. Refactor the code to also support other types.

tgt-vvp: Support nested lvalues for all property types

---

elab_expr.cc
ivtest/ivltests/cast_real_invalid1.v
ivtest/ivltests/cast_real_invalid2.v
ivtest/ivltests/cast_real_invalid3.v
ivtest/ivltests/cast_real_invalid4.v
ivtest/regress-vvp.list
ivtest/vvp_tests/cast_real_invalid1.json
ivtest/vvp_tests/cast_real_invalid2.json
ivtest/vvp_tests/cast_real_invalid3.json
ivtest/vvp_tests/cast_real_invalid4.json

Only vector types can be cast to real. Report an error when trying to cast
a different type instead of triggering an assert later on.

Reject invalid casts to real

---

ivtest/regress-sv.list

Just some minor typos I stumbled upon in `regress-sv.list`.

Typos in regress-sv.list

---

ivtest/ivltests/pr1008.v

This updates pr1008.v test to add a `$finish`.
This is because this test is part of the sv-test suite, and without it, as written, it causes Verilator to run this test forever, because Verilator schedules this assignment every cycle, instead of in an IEEE-compliant event-sensitive way.   I realize that's an IEEE-compliance bug with Verilator, but not something Verilator plans on changing due to performance concerns in other cases.
I thought it's worth trying this pull to avoid consuming sv-test's CPU time spinning until a timeout every night.
As far as I can tell this is the only remaining hang in Verilator running the ivtest suite (the final other remaining one was a bug fixed today).
I don't think this changes the intent of the test as was written, but I completely understand if you …

Update pr1008.v test to $finish
